<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class frmMainSpc
    Inherits System.Windows.Forms.Form

    'Form reemplaza a Dispose para limpiar la lista de componentes.
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub


    'Requerido por el Diseñador de Windows Forms
    Private components As System.ComponentModel.IContainer

    'NOTA: el Diseñador de Windows Forms necesita el siguiente procedimiento
    'Se puede modificar usando el Diseñador de Windows Forms.  
    'No lo modifique con el editor de código.
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container()
        Dim UltraStatusPanel1 As Infragistics.Win.UltraWinStatusBar.UltraStatusPanel = New Infragistics.Win.UltraWinStatusBar.UltraStatusPanel()
        Dim Appearance117 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(frmMainSpc))
        Dim UltraStatusPanel2 As Infragistics.Win.UltraWinStatusBar.UltraStatusPanel = New Infragistics.Win.UltraWinStatusBar.UltraStatusPanel()
        Dim Appearance118 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim UltraStatusPanel3 As Infragistics.Win.UltraWinStatusBar.UltraStatusPanel = New Infragistics.Win.UltraWinStatusBar.UltraStatusPanel()
        Dim Appearance119 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim UltraStatusPanel4 As Infragistics.Win.UltraWinStatusBar.UltraStatusPanel = New Infragistics.Win.UltraWinStatusBar.UltraStatusPanel()
        Dim Appearance120 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool77 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.SAL")
        Dim ButtonTool140 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.ACT")
        Dim RibbonTab1 As Infragistics.Win.UltraWinToolbars.RibbonTab = New Infragistics.Win.UltraWinToolbars.RibbonTab("SPC.CAT")
        Dim RibbonGroup1 As Infragistics.Win.UltraWinToolbars.RibbonGroup = New Infragistics.Win.UltraWinToolbars.RibbonGroup("SPC.CAT.CAT")
        Dim ButtonTool7 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.CAT.TDA")
        Dim ButtonTool3 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.CAT.AER")
        Dim ButtonTool5 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.CAT.AVI")
        Dim ButtonTool1 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.CAT.PDE")
        Dim ButtonTool18 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.CAT.MDE")
        Dim ButtonTool17 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.CAT.GDP")
        Dim ButtonTool21 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.CAT.PRO")
        Dim RibbonGroup2 As Infragistics.Win.UltraWinToolbars.RibbonGroup = New Infragistics.Win.UltraWinToolbars.RibbonGroup("SPC.CAT.REG")
        Dim ButtonTool42 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.REG.CON")
        Dim ButtonTool148 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.REG.CAR")
        Dim ButtonTool6 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.REG.DES")
        Dim ButtonTool26 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.REG.CAM")
        Dim ButtonTool138 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.REG.MUL")
        Dim ButtonTool41 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.REG.ELE")
        Dim ButtonTool109 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.REG.PES")
        Dim RibbonGroup3 As Infragistics.Win.UltraWinToolbars.RibbonGroup = New Infragistics.Win.UltraWinToolbars.RibbonGroup("SPC.CAT.OTR")
        Dim ButtonTool16 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.OTR.TAR")
        Dim ButtonTool122 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.OTR.PAI")
        Dim ButtonTool54 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.OTR.CIU")
        Dim ButtonTool152 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.OTR.PER")
        Dim ButtonTool23 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.OTR.USU")
        Dim ButtonTool19 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.OTR.MDS")
        Dim ButtonTool182 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.OTR.CNT")
        Dim RibbonTab2 As Infragistics.Win.UltraWinToolbars.RibbonTab = New Infragistics.Win.UltraWinToolbars.RibbonTab("SPC.CYE")
        Dim RibbonGroup4 As Infragistics.Win.UltraWinToolbars.RibbonGroup = New Infragistics.Win.UltraWinToolbars.RibbonGroup("SPC.CYE.DAP")
        Dim ButtonTool156 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CYE.DAP.AGE")
        Dim ButtonTool49 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CYE.DAP.AE")
        Dim ButtonTool51 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CYE.CYE.ADC")
        Dim ButtonTool53 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CYE.CYE.INS")
        Dim ButtonTool120 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CYE.CYE.ADS")
        Dim ButtonTool158 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CYE.CYE.SDR")
        Dim ButtonTool159 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CYE.CYE.ADT")
        Dim ButtonTool164 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CYE.CYE.CPE")
        Dim RibbonTab3 As Infragistics.Win.UltraWinToolbars.RibbonTab = New Infragistics.Win.UltraWinToolbars.RibbonTab("SPC.MOV")
        Dim RibbonGroup5 As Infragistics.Win.UltraWinToolbars.RibbonGroup = New Infragistics.Win.UltraWinToolbars.RibbonGroup("SPC.MOV.MOV")
        Dim ButtonTool61 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.MOV.MOV.EDP")
        Dim ButtonTool62 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.MOV.MOV.MDC")
        Dim ButtonTool63 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.MOV.MOV.DDC")
        Dim RibbonTab4 As Infragistics.Win.UltraWinToolbars.RibbonTab = New Infragistics.Win.UltraWinToolbars.RibbonTab("SPC.PRO")
        Dim RibbonGroup6 As Infragistics.Win.UltraWinToolbars.RibbonGroup = New Infragistics.Win.UltraWinToolbars.RibbonGroup("SPC.PRO.PRO")
        Dim ButtonTool130 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.PRO.BDV")
        Dim ButtonTool136 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.PRO.PAE")
        Dim ButtonTool131 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.PRO.PSE")
        Dim ButtonTool81 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.PRO.RDC")
        Dim ButtonTool82 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.PRO.CDP")
        Dim ButtonTool190 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.PRO.AGS")
        Dim ButtonTool134 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.PRO.SDE")
        Dim ButtonTool124 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.PRO.CPE")
        Dim ButtonTool84 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.PRO.RDM")
        Dim ButtonTool127 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.PRO.ACA")
        Dim ButtonTool83 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.PRO.RDV")
        Dim ButtonTool178 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.PRO.SCC")
        Dim ButtonTool180 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.PRO.MCC")
        Dim ButtonTool183 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.PRO.RAV")
        Dim RibbonGroup7 As Infragistics.Win.UltraWinToolbars.RibbonGroup = New Infragistics.Win.UltraWinToolbars.RibbonGroup("SPC.PRO.ULD")
        Dim ButtonTool91 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.ULD.ENT")
        Dim ButtonTool92 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.ULD.SAL")
        Dim RibbonTab5 As Infragistics.Win.UltraWinToolbars.RibbonTab = New Infragistics.Win.UltraWinToolbars.RibbonTab("SPC.REP")
        Dim RibbonGroup8 As Infragistics.Win.UltraWinToolbars.RibbonGroup = New Infragistics.Win.UltraWinToolbars.RibbonGroup("SPC.REP.REP")
        Dim ButtonTool100 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.REP.REP.DEC")
        Dim ButtonTool96 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.REP.REP.DET")
        Dim ButtonTool95 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.REP.REP.RES")
        Dim ButtonTool97 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.REP.REP.SDE")
        Dim ButtonTool144 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.REP.REP.SDET")
        Dim ButtonTool142 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.REP.REP.HDE")
        Dim ButtonTool112 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.REP.REP.RDPP")
        Dim ButtonTool118 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.REP.REP.VDP")
        Dim ButtonTool22 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.REP.REP.RDP")
        Dim ButtonTool149 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.REP.REP.PEZ")
        Dim ButtonTool150 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.REP.REP.HPZ")
        Dim ButtonTool166 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.REP.REP.RTP")
        Dim ButtonTool186 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.REP.REP.RDP2")
        Dim RibbonTab6 As Infragistics.Win.UltraWinToolbars.RibbonTab = New Infragistics.Win.UltraWinToolbars.RibbonTab("SPC.ADM")
        Dim RibbonGroup9 As Infragistics.Win.UltraWinToolbars.RibbonGroup = New Infragistics.Win.UltraWinToolbars.RibbonGroup("SPC.ADM.CON")
        Dim ButtonTool39 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.ADM.CON.GEN")
        Dim ButtonTool65 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.ADM.CON.BAL")
        Dim ButtonTool111 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.ADM.CON.COR")
        Dim RibbonGroup10 As Infragistics.Win.UltraWinToolbars.RibbonGroup = New Infragistics.Win.UltraWinToolbars.RibbonGroup("SPC.ADM.GEN")
        Dim ButtonTool64 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.ADM.GEN.TUR")
        Dim ButtonTool76 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.ADM.GEN.ATP")
        Dim ButtonTool99 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.ADM.GEN.CTP")
        Dim ButtonTool67 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.ADM.GEN.MDE")
        Dim ButtonTool154 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.ADM.GEN.FAC")
        Dim RibbonGroup11 As Infragistics.Win.UltraWinToolbars.RibbonGroup = New Infragistics.Win.UltraWinToolbars.RibbonGroup("SPC.ADM.FAC")
        Dim ButtonTool168 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.ADM.FAC.CLI")
        Dim ButtonTool169 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.ADM.FAC.SER")
        Dim ButtonTool172 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.ADM.FAC.PER")
        Dim ButtonTool174 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.ADM.FAC.PCS")
        Dim ButtonTool176 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.ADM.FAC.PFT")
        Dim ButtonTool2 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.CAT.AER-1")
        Dim Appearance121 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool4 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.CAT.AER")
        Dim Appearance122 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool10 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.CAT.AVI")
        Dim Appearance123 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool11 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.REG.CAM")
        Dim Appearance124 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool12 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.CAT.COM")
        Dim ButtonTool13 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.CAT.DTP")
        Dim ButtonTool14 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.CAT.DES")
        Dim Appearance125 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ComboBoxTool2 As Infragistics.Win.UltraWinToolbars.ComboBoxTool = New Infragistics.Win.UltraWinToolbars.ComboBoxTool("MAN.CAT.CAT.COMp")
        Dim ValueList1 As Infragistics.Win.ValueList = New Infragistics.Win.ValueList(0)
        Dim ButtonTool27 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.REG.MUL")
        Dim Appearance126 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool28 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.REG.ELE")
        Dim Appearance127 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool29 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.CAT.GDP")
        Dim Appearance128 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool30 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.CAT.MDE")
        Dim Appearance129 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool31 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.OTR.PAI")
        Dim Appearance130 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool32 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.CAT.POS")
        Dim Appearance131 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool33 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.CAT.PRO")
        Dim Appearance132 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool34 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.CAT.TDE")
        Dim Appearance133 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool35 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.OTR.CIU")
        Dim Appearance134 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool36 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.CAT.PVO")
        Dim Appearance135 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool37 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.CAT.TAR")
        Dim Appearance136 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool38 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.OTR.MDS")
        Dim Appearance137 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool43 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("MAN.CAT.COM.AER")
        Dim Appearance138 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool44 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.COM.ADC")
        Dim Appearance139 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool45 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.COM.INS")
        Dim Appearance140 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool46 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.COM.SEG")
        Dim Appearance141 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool47 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.COM.SDR")
        Dim Appearance142 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool48 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.COM.TRA")
        Dim Appearance143 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool55 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CYE.DAP.GEA")
        Dim Appearance144 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool56 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CYE.DAP.AER")
        Dim Appearance145 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool57 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CYE.DAP.ADC")
        Dim Appearance146 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool58 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CYE.DAP.INS")
        Dim Appearance147 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool59 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CYE.DAP.SDR")
        Dim Appearance148 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool60 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.COM.PTRA")
        Dim Appearance149 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool68 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.MOV.MOV.EDP")
        Dim Appearance150 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim Appearance151 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool69 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.MOV.MOV.MDC")
        Dim Appearance152 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool70 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.MOV.MOV.DDC")
        Dim Appearance153 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool71 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.MOV.MOV.SDB")
        Dim Appearance154 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool72 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.PRO.BDV")
        Dim Appearance155 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim Appearance156 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool73 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.MOV.MOV.TDP")
        Dim Appearance157 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool74 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.MOV.MOV.SDP")
        Dim Appearance158 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool78 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("MAN.INI")
        Dim Appearance159 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool79 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("MAN:CDC")
        Dim Appearance160 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool80 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.SAL")
        Dim Appearance161 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool86 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.PRO.RDC")
        Dim Appearance162 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool87 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.PRO.CDP")
        Dim Appearance163 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool88 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.PRO.RDV")
        Dim Appearance164 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool90 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.PRO.EDL")
        Dim Appearance165 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool93 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.ULD.ENT")
        Dim Appearance166 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool94 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.ULD.SAL")
        Dim Appearance167 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool102 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.REP.REP.RES")
        Dim Appearance168 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim Appearance169 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool103 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.REP.REP.DET")
        Dim Appearance170 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim Appearance171 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool104 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.REP.REP.SDE")
        Dim Appearance172 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim Appearance173 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool105 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.REP.REP.IDE")
        Dim Appearance174 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim Appearance175 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool106 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.REP.REP.PFA")
        Dim Appearance176 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim Appearance177 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool107 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.REP.REP.DEC")
        Dim Appearance178 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool108 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.REP.REP.SEG")
        Dim Appearance179 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim Appearance180 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool114 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.REP.IND.AGE")
        Dim Appearance181 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim Appearance182 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool115 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.REP.IND.DDV")
        Dim Appearance183 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim Appearance184 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool116 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.REP.IND.DES")
        Dim Appearance185 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim Appearance186 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool117 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.REP.REP.HDE")
        Dim Appearance187 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool9 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.CAT.PDE")
        Dim Appearance188 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool24 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.CAT.TDA")
        Dim Appearance189 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool119 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.REG.CON")
        Dim Appearance190 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool121 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CYE.DAP.SEG")
        Dim Appearance191 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool123 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.COM.OTR")
        Dim ButtonTool125 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.MOV.MOV.ASG")
        Dim ButtonTool126 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.PRO.ACA-1")
        Dim ButtonTool128 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.PRO.ACA")
        Dim Appearance192 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool129 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.PRO.PSE")
        Dim Appearance193 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool85 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.ADM.CON.BAL")
        Dim Appearance194 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool133 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.PRO.CPE")
        Dim Appearance195 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool135 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.PRO.SDE")
        Dim Appearance196 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool137 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.PRO.PAE")
        Dim Appearance197 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool139 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.OTR.USU")
        Dim Appearance198 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool141 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.ACT")
        Dim Appearance199 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool145 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.REP.REP.SDET")
        Dim Appearance200 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool113 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.REP.REP.RDPP")
        Dim Appearance201 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool143 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.REP.REP.VDP")
        Dim Appearance202 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool8 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("Material de Elementos")
        Dim ButtonTool15 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.REG.DES")
        Dim Appearance203 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool20 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.OTR.TAR")
        Dim Appearance204 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool25 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.REP.REP.RDP")
        Dim Appearance205 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool40 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.REP.REP.PEZ")
        Dim Appearance206 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool147 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.REP.REP.HPZ")
        Dim Appearance207 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool146 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.ADM.CON.GEN")
        Dim Appearance208 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool151 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.REG.CAR")
        Dim Appearance209 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool153 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.OTR.PER")
        Dim Appearance210 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool89 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.PRO.RDM")
        Dim Appearance211 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool66 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.ADM.GEN.TUR")
        Dim Appearance212 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool75 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.ADM.GEN.MDE")
        Dim Appearance213 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool98 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.ADM.GEN.ATP")
        Dim Appearance214 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool101 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.ADM.GEN.CTP")
        Dim Appearance215 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool110 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.REG.PES")
        Dim Appearance216 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool132 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.ADM.CON.COR")
        Dim Appearance229 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool155 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.ADM.GEN.FAC")
        Dim Appearance230 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool157 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CYE.DAP.AGE")
        Dim Appearance231 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool50 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CYE.DAP.AE")
        Dim Appearance232 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool52 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CYE.CYE.ADC")
        Dim Appearance233 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool160 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CYE.CYE.INS")
        Dim Appearance234 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool161 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CYE.CYE.ADS")
        Dim Appearance235 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool162 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CYE.CYE.SDR")
        Dim Appearance236 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool163 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CYE.CYE.ADT")
        Dim Appearance237 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool165 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CYE.CYE.CPE")
        Dim Appearance238 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool167 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.REP.REP.RTP")
        Dim Appearance239 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool170 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.ADM.FAC.CLI")
        Dim Appearance240 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool171 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.ADM.FAC.SER")
        Dim Appearance241 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool173 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.ADM.FAC.PER")
        Dim Appearance242 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool175 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.ADM.FAC.PCS")
        Dim Appearance243 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool177 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.ADM.FAC.PFT")
        Dim Appearance244 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool179 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.PRO.SCC")
        Dim Appearance245 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool181 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.PRO.MCC")
        Dim Appearance246 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool184 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.CAT.OTR.CNT")
        Dim Appearance11 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool185 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.PRO.RAV")
        Dim Appearance12 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool187 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.REP.REP.RDP2")
        Dim Appearance13 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim ButtonTool191 As Infragistics.Win.UltraWinToolbars.ButtonTool = New Infragistics.Win.UltraWinToolbars.ButtonTool("SPC.PRO.PRO.AGS")
        Dim Appearance14 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Dim Appearance15 As Infragistics.Win.Appearance = New Infragistics.Win.Appearance()
        Me.pnlMain = New Infragistics.Win.Misc.UltraPanel()
        Me.usbPrincipal = New Infragistics.Win.UltraWinStatusBar.UltraStatusBar()
        Me._frmMainSpc_Toolbars_Dock_Area_Right = New Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea()
        Me.UtmMain = New Infragistics.Win.UltraWinToolbars.UltraToolbarsManager(Me.components)
        Me._frmMainSpc_Toolbars_Dock_Area_Left = New Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea()
        Me._frmMainSpc_Toolbars_Dock_Area_Bottom = New Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea()
        Me._frmMainSpc_Toolbars_Dock_Area_Top = New Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea()
        Me.pnlMain.SuspendLayout()
        CType(Me.usbPrincipal, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.UtmMain, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'pnlMain
        '
        Me.pnlMain.Cursor = System.Windows.Forms.Cursors.Default
        Me.pnlMain.Dock = System.Windows.Forms.DockStyle.Fill
        Me.pnlMain.Location = New System.Drawing.Point(4, 158)
        Me.pnlMain.Name = "pnlMain"
        Me.pnlMain.Size = New System.Drawing.Size(955, 286)
        Me.pnlMain.TabIndex = 0
        '
        'usbPrincipal
        '
        Me.usbPrincipal.Location = New System.Drawing.Point(0, 444)
        Me.usbPrincipal.Name = "usbPrincipal"
        Appearance117.Image = CType(resources.GetObject("Appearance117.Image"), Object)
        UltraStatusPanel1.Appearance = Appearance117
        UltraStatusPanel1.Key = "USB.TRM"
        UltraStatusPanel1.Padding = New System.Drawing.Size(10, 0)
        UltraStatusPanel1.SizingMode = Infragistics.Win.UltraWinStatusBar.PanelSizingMode.Automatic
        UltraStatusPanel1.Text = "TERMINAL"
        Appearance118.Image = CType(resources.GetObject("Appearance118.Image"), Object)
        UltraStatusPanel2.Appearance = Appearance118
        UltraStatusPanel2.Key = "USB.USER"
        UltraStatusPanel2.Padding = New System.Drawing.Size(10, 0)
        UltraStatusPanel2.SizingMode = Infragistics.Win.UltraWinStatusBar.PanelSizingMode.Automatic
        UltraStatusPanel2.Text = "Usuario"
        Appearance119.Image = CType(resources.GetObject("Appearance119.Image"), Object)
        UltraStatusPanel3.Appearance = Appearance119
        UltraStatusPanel3.DateTimeFormat = "dd/MM/yyyy HH:mm:ss"
        UltraStatusPanel3.Key = "USB.DAT"
        UltraStatusPanel3.Padding = New System.Drawing.Size(10, 0)
        UltraStatusPanel3.Style = Infragistics.Win.UltraWinStatusBar.PanelStyle.[Date]
        UltraStatusPanel3.ToolTipText = "Fecha y Hora"
        UltraStatusPanel3.Width = 148
        Appearance120.Image = CType(resources.GetObject("Appearance120.Image"), Object)
        UltraStatusPanel4.Appearance = Appearance120
        UltraStatusPanel4.Key = "USB.VER"
        UltraStatusPanel4.Padding = New System.Drawing.Size(10, 0)
        UltraStatusPanel4.SizingMode = Infragistics.Win.UltraWinStatusBar.PanelSizingMode.Automatic
        UltraStatusPanel4.Text = "Versión"
        Me.usbPrincipal.Panels.AddRange(New Infragistics.Win.UltraWinStatusBar.UltraStatusPanel() {UltraStatusPanel1, UltraStatusPanel2, UltraStatusPanel3, UltraStatusPanel4})
        Me.usbPrincipal.Size = New System.Drawing.Size(963, 23)
        Me.usbPrincipal.TabIndex = 5
        Me.usbPrincipal.Text = "UltraStatusBar1"
        Me.usbPrincipal.ViewStyle = Infragistics.Win.UltraWinStatusBar.ViewStyle.Office2007
        '
        '_frmMainSpc_Toolbars_Dock_Area_Right
        '
        Me._frmMainSpc_Toolbars_Dock_Area_Right.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping
        Me._frmMainSpc_Toolbars_Dock_Area_Right.BackColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(219, Byte), Integer), CType(CType(255, Byte), Integer))
        Me._frmMainSpc_Toolbars_Dock_Area_Right.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Right
        Me._frmMainSpc_Toolbars_Dock_Area_Right.ForeColor = System.Drawing.SystemColors.ControlText
        Me._frmMainSpc_Toolbars_Dock_Area_Right.InitialResizeAreaExtent = 4
        Me._frmMainSpc_Toolbars_Dock_Area_Right.Location = New System.Drawing.Point(959, 158)
        Me._frmMainSpc_Toolbars_Dock_Area_Right.Name = "_frmMainSpc_Toolbars_Dock_Area_Right"
        Me._frmMainSpc_Toolbars_Dock_Area_Right.Size = New System.Drawing.Size(4, 286)
        Me._frmMainSpc_Toolbars_Dock_Area_Right.ToolbarsManager = Me.UtmMain
        '
        'UtmMain
        '
        Me.UtmMain.DesignerFlags = 1
        Me.UtmMain.DockWithinContainer = Me
        Me.UtmMain.DockWithinContainerBaseType = GetType(System.Windows.Forms.Form)
        Me.UtmMain.Office2007UICompatibility = False
        Me.UtmMain.Ribbon.ApplicationMenu.ToolAreaLeft.NonInheritedTools.AddRange(New Infragistics.Win.UltraWinToolbars.ToolBase() {ButtonTool77, ButtonTool140})
        Me.UtmMain.Ribbon.ApplicationMenuButtonImage = CType(resources.GetObject("UtmMain.Ribbon.ApplicationMenuButtonImage"), System.Drawing.Image)
        RibbonTab1.Caption = "Catálogos"
        RibbonGroup1.Caption = "Catálogos"
        ButtonTool3.InstanceProps.IsFirstInGroup = True
        ButtonTool18.InstanceProps.IsFirstInGroup = True
        ButtonTool17.InstanceProps.IsFirstInGroup = True
        RibbonGroup1.Tools.AddRange(New Infragistics.Win.UltraWinToolbars.ToolBase() {ButtonTool7, ButtonTool3, ButtonTool5, ButtonTool1, ButtonTool18, ButtonTool17, ButtonTool21})
        RibbonGroup2.Caption = "Registros"
        ButtonTool42.InstanceProps.IsFirstInGroup = True
        ButtonTool26.InstanceProps.IsFirstInGroup = True
        RibbonGroup2.Tools.AddRange(New Infragistics.Win.UltraWinToolbars.ToolBase() {ButtonTool42, ButtonTool148, ButtonTool6, ButtonTool26, ButtonTool138, ButtonTool41, ButtonTool109})
        RibbonGroup3.Caption = "Otros"
        ButtonTool16.InstanceProps.IsFirstInGroup = True
        ButtonTool122.InstanceProps.IsFirstInGroup = True
        ButtonTool152.InstanceProps.IsFirstInGroup = True
        RibbonGroup3.Tools.AddRange(New Infragistics.Win.UltraWinToolbars.ToolBase() {ButtonTool16, ButtonTool122, ButtonTool54, ButtonTool152, ButtonTool23, ButtonTool19, ButtonTool182})
        RibbonTab1.Groups.AddRange(New Infragistics.Win.UltraWinToolbars.RibbonGroup() {RibbonGroup1, RibbonGroup2, RibbonGroup3})
        RibbonTab2.Caption = "Compañias y empleados"
        RibbonGroup4.Caption = "Datos Personales"
        ButtonTool156.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool49.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool51.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool53.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool120.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool158.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool159.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool164.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        RibbonGroup4.Tools.AddRange(New Infragistics.Win.UltraWinToolbars.ToolBase() {ButtonTool156, ButtonTool49, ButtonTool51, ButtonTool53, ButtonTool120, ButtonTool158, ButtonTool159, ButtonTool164})
        RibbonTab2.Groups.AddRange(New Infragistics.Win.UltraWinToolbars.RibbonGroup() {RibbonGroup4})
        RibbonTab3.Caption = "Movimientos"
        RibbonGroup5.Caption = "Movimientos"
        ButtonTool61.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool62.InstanceProps.IsFirstInGroup = True
        ButtonTool62.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool63.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        RibbonGroup5.Tools.AddRange(New Infragistics.Win.UltraWinToolbars.ToolBase() {ButtonTool61, ButtonTool62, ButtonTool63})
        RibbonTab3.Groups.AddRange(New Infragistics.Win.UltraWinToolbars.RibbonGroup() {RibbonGroup5})
        RibbonTab4.Caption = "Procesos"
        RibbonGroup6.Caption = "Procesos"
        ButtonTool130.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool136.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool131.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool81.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool82.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool190.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool134.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool124.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool84.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool127.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool83.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool178.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool180.InstanceProps.MinimumSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool183.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        RibbonGroup6.Tools.AddRange(New Infragistics.Win.UltraWinToolbars.ToolBase() {ButtonTool130, ButtonTool136, ButtonTool131, ButtonTool81, ButtonTool82, ButtonTool190, ButtonTool134, ButtonTool124, ButtonTool84, ButtonTool127, ButtonTool83, ButtonTool178, ButtonTool180, ButtonTool183})
        RibbonGroup7.Caption = "ULD"
        ButtonTool91.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool92.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        RibbonGroup7.Tools.AddRange(New Infragistics.Win.UltraWinToolbars.ToolBase() {ButtonTool91, ButtonTool92})
        RibbonTab4.Groups.AddRange(New Infragistics.Win.UltraWinToolbars.RibbonGroup() {RibbonGroup6, RibbonGroup7})
        RibbonTab5.Caption = "Reportes"
        RibbonGroup8.Caption = "Reportes"
        ButtonTool100.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool96.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool95.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool97.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool144.InstanceProps.MinimumSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool142.InstanceProps.MinimumSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool112.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool118.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool22.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool149.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool150.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool166.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool186.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        RibbonGroup8.Tools.AddRange(New Infragistics.Win.UltraWinToolbars.ToolBase() {ButtonTool100, ButtonTool96, ButtonTool95, ButtonTool97, ButtonTool144, ButtonTool142, ButtonTool112, ButtonTool118, ButtonTool22, ButtonTool149, ButtonTool150, ButtonTool166, ButtonTool186})
        RibbonTab5.Groups.AddRange(New Infragistics.Win.UltraWinToolbars.RibbonGroup() {RibbonGroup8})
        RibbonTab6.Caption = "Administración"
        RibbonGroup9.Caption = "Configuraciones"
        ButtonTool39.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool65.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool111.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        RibbonGroup9.Tools.AddRange(New Infragistics.Win.UltraWinToolbars.ToolBase() {ButtonTool39, ButtonTool65, ButtonTool111})
        RibbonGroup10.Caption = "Generalair"
        ButtonTool64.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool76.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool99.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool67.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool154.InstanceProps.PreferredSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        RibbonGroup10.Tools.AddRange(New Infragistics.Win.UltraWinToolbars.ToolBase() {ButtonTool64, ButtonTool76, ButtonTool99, ButtonTool67, ButtonTool154})
        RibbonGroup11.Caption = "Facturacion"
        ButtonTool168.InstanceProps.MinimumSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool169.InstanceProps.MinimumSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool172.InstanceProps.MinimumSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool174.InstanceProps.MinimumSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        ButtonTool176.InstanceProps.MinimumSizeOnRibbon = Infragistics.Win.UltraWinToolbars.RibbonToolSize.Large
        RibbonGroup11.Tools.AddRange(New Infragistics.Win.UltraWinToolbars.ToolBase() {ButtonTool168, ButtonTool169, ButtonTool172, ButtonTool174, ButtonTool176})
        RibbonTab6.Groups.AddRange(New Infragistics.Win.UltraWinToolbars.RibbonGroup() {RibbonGroup9, RibbonGroup10, RibbonGroup11})
        Me.UtmMain.Ribbon.NonInheritedRibbonTabs.AddRange(New Infragistics.Win.UltraWinToolbars.RibbonTab() {RibbonTab1, RibbonTab2, RibbonTab3, RibbonTab4, RibbonTab5, RibbonTab6})
        Me.UtmMain.Ribbon.Visible = True
        Me.UtmMain.ShowFullMenusDelay = 500
        Appearance121.Image = CType(resources.GetObject("Appearance121.Image"), Object)
        ButtonTool2.SharedPropsInternal.AppearancesSmall.Appearance = Appearance121
        ButtonTool2.SharedPropsInternal.Caption = "Aerolineas"
        Appearance122.Image = CType(resources.GetObject("Appearance122.Image"), Object)
        ButtonTool4.SharedPropsInternal.AppearancesSmall.Appearance = Appearance122
        ButtonTool4.SharedPropsInternal.Caption = "Aeropuertos"
        Appearance123.Image = CType(resources.GetObject("Appearance123.Image"), Object)
        ButtonTool10.SharedPropsInternal.AppearancesSmall.Appearance = Appearance123
        ButtonTool10.SharedPropsInternal.Caption = "Aviones"
        Appearance124.Image = CType(resources.GetObject("Appearance124.Image"), Object)
        ButtonTool11.SharedPropsInternal.AppearancesSmall.Appearance = Appearance124
        ButtonTool11.SharedPropsInternal.Caption = "Camiones"
        ButtonTool13.SharedPropsInternal.Caption = "Datos Personales"
        Appearance125.Image = CType(resources.GetObject("Appearance125.Image"), Object)
        ButtonTool14.SharedPropsInternal.AppearancesSmall.Appearance = Appearance125
        ButtonTool14.SharedPropsInternal.Caption = "Destinos"
        ComboBoxTool2.SharedPropsInternal.Caption = "Compañias"
        ValueList1.PreferredDropDownSize = New System.Drawing.Size(0, 0)
        ComboBoxTool2.ValueList = ValueList1
        Appearance126.Image = CType(resources.GetObject("Appearance126.Image"), Object)
        ButtonTool27.SharedPropsInternal.AppearancesSmall.Appearance = Appearance126
        ButtonTool27.SharedPropsInternal.Caption = "Mulas"
        Appearance127.Image = CType(resources.GetObject("Appearance127.Image"), Object)
        ButtonTool28.SharedPropsInternal.AppearancesSmall.Appearance = Appearance127
        ButtonTool28.SharedPropsInternal.Caption = "Elementos"
        Appearance128.Image = CType(resources.GetObject("Appearance128.Image"), Object)
        ButtonTool29.SharedPropsInternal.AppearancesSmall.Appearance = Appearance128
        ButtonTool29.SharedPropsInternal.Caption = "Grupo de Productos"
        Appearance129.Image = CType(resources.GetObject("Appearance129.Image"), Object)
        ButtonTool30.SharedPropsInternal.AppearancesSmall.Appearance = Appearance129
        ButtonTool30.SharedPropsInternal.Caption = "Material del Elemento"
        Appearance130.Image = CType(resources.GetObject("Appearance130.Image"), Object)
        ButtonTool31.SharedPropsInternal.AppearancesSmall.Appearance = Appearance130
        ButtonTool31.SharedPropsInternal.Caption = "Países"
        Appearance131.Image = CType(resources.GetObject("Appearance131.Image"), Object)
        ButtonTool32.SharedPropsInternal.AppearancesSmall.Appearance = Appearance131
        ButtonTool32.SharedPropsInternal.Caption = "Posiciones"
        Appearance132.Image = CType(resources.GetObject("Appearance132.Image"), Object)
        ButtonTool33.SharedPropsInternal.AppearancesSmall.Appearance = Appearance132
        ButtonTool33.SharedPropsInternal.Caption = "Productos"
        Appearance133.Image = CType(resources.GetObject("Appearance133.Image"), Object)
        ButtonTool34.SharedPropsInternal.AppearancesSmall.Appearance = Appearance133
        ButtonTool34.SharedPropsInternal.Caption = "Tipos de Elemento"
        Appearance134.Image = CType(resources.GetObject("Appearance134.Image"), Object)
        ButtonTool35.SharedPropsInternal.AppearancesSmall.Appearance = Appearance134
        ButtonTool35.SharedPropsInternal.Caption = "Ciudades"
        Appearance135.Image = CType(resources.GetObject("Appearance135.Image"), Object)
        ButtonTool36.SharedPropsInternal.AppearancesSmall.Appearance = Appearance135
        ButtonTool36.SharedPropsInternal.Caption = "Peso Volumén"
        Appearance136.Image = CType(resources.GetObject("Appearance136.Image"), Object)
        ButtonTool37.SharedPropsInternal.AppearancesSmall.Appearance = Appearance136
        ButtonTool37.SharedPropsInternal.Caption = "Tarifas"
        Appearance137.Image = CType(resources.GetObject("Appearance137.Image"), Object)
        ButtonTool38.SharedPropsInternal.AppearancesSmall.Appearance = Appearance137
        ButtonTool38.SharedPropsInternal.Caption = "Matriz de Seguridad"
        Appearance138.Image = CType(resources.GetObject("Appearance138.Image"), Object)
        ButtonTool43.SharedPropsInternal.AppearancesSmall.Appearance = Appearance138
        ButtonTool43.SharedPropsInternal.Caption = "Aerolineas"
        Appearance139.Image = CType(resources.GetObject("Appearance139.Image"), Object)
        ButtonTool44.SharedPropsInternal.AppearancesSmall.Appearance = Appearance139
        ButtonTool44.SharedPropsInternal.Caption = "Agencias de Carga"
        Appearance140.Image = CType(resources.GetObject("Appearance140.Image"), Object)
        ButtonTool45.SharedPropsInternal.AppearancesSmall.Appearance = Appearance140
        ButtonTool45.SharedPropsInternal.Caption = "Institución"
        Appearance141.Image = CType(resources.GetObject("Appearance141.Image"), Object)
        ButtonTool46.SharedPropsInternal.AppearancesSmall.Appearance = Appearance141
        ButtonTool46.SharedPropsInternal.Caption = "Seguridad"
        Appearance142.Image = CType(resources.GetObject("Appearance142.Image"), Object)
        ButtonTool47.SharedPropsInternal.AppearancesSmall.Appearance = Appearance142
        ButtonTool47.SharedPropsInternal.Caption = "Servicio de Rampa"
        Appearance143.Image = CType(resources.GetObject("Appearance143.Image"), Object)
        ButtonTool48.SharedPropsInternal.AppearancesSmall.Appearance = Appearance143
        ButtonTool48.SharedPropsInternal.Caption = "Transportista"
        Appearance144.Image = CType(resources.GetObject("Appearance144.Image"), Object)
        ButtonTool55.SharedPropsInternal.AppearancesSmall.Appearance = Appearance144
        ButtonTool55.SharedPropsInternal.Caption = "General Air"
        Appearance145.Image = CType(resources.GetObject("Appearance145.Image"), Object)
        ButtonTool56.SharedPropsInternal.AppearancesSmall.Appearance = Appearance145
        ButtonTool56.SharedPropsInternal.Caption = "Aerolíneas"
        Appearance146.Image = CType(resources.GetObject("Appearance146.Image"), Object)
        ButtonTool57.SharedPropsInternal.AppearancesSmall.Appearance = Appearance146
        ButtonTool57.SharedPropsInternal.Caption = "Agencias de Carga"
        Appearance147.Image = CType(resources.GetObject("Appearance147.Image"), Object)
        ButtonTool58.SharedPropsInternal.AppearancesSmall.Appearance = Appearance147
        ButtonTool58.SharedPropsInternal.Caption = "Instituciones"
        Appearance148.Image = CType(resources.GetObject("Appearance148.Image"), Object)
        ButtonTool59.SharedPropsInternal.AppearancesSmall.Appearance = Appearance148
        ButtonTool59.SharedPropsInternal.Caption = "Servicio de Rampa"
        Appearance149.Image = CType(resources.GetObject("Appearance149.Image"), Object)
        ButtonTool60.SharedPropsInternal.AppearancesSmall.Appearance = Appearance149
        ButtonTool60.SharedPropsInternal.Caption = "Transportistas"
        Appearance150.Image = CType(resources.GetObject("Appearance150.Image"), Object)
        ButtonTool68.SharedPropsInternal.AppearancesLarge.Appearance = Appearance150
        Appearance151.Image = CType(resources.GetObject("Appearance151.Image"), Object)
        ButtonTool68.SharedPropsInternal.AppearancesSmall.Appearance = Appearance151
        ButtonTool68.SharedPropsInternal.Caption = "Entrada de Pallets"
        Appearance152.Image = CType(resources.GetObject("Appearance152.Image"), Object)
        ButtonTool69.SharedPropsInternal.AppearancesSmall.Appearance = Appearance152
        ButtonTool69.SharedPropsInternal.Caption = "Movimiento de Carga"
        Appearance153.Image = CType(resources.GetObject("Appearance153.Image"), Object)
        ButtonTool70.SharedPropsInternal.AppearancesSmall.Appearance = Appearance153
        ButtonTool70.SharedPropsInternal.Caption = "Devolución de Carga"
        Appearance154.Image = CType(resources.GetObject("Appearance154.Image"), Object)
        ButtonTool71.SharedPropsInternal.AppearancesSmall.Appearance = Appearance154
        ButtonTool71.SharedPropsInternal.Caption = "Salida de Bodega"
        Appearance155.Image = CType(resources.GetObject("Appearance155.Image"), Object)
        ButtonTool72.SharedPropsInternal.AppearancesLarge.Appearance = Appearance155
        Appearance156.Image = CType(resources.GetObject("Appearance156.Image"), Object)
        ButtonTool72.SharedPropsInternal.AppearancesSmall.Appearance = Appearance156
        ButtonTool72.SharedPropsInternal.Caption = "Briefing de Vuelos"
        Appearance157.Image = CType(resources.GetObject("Appearance157.Image"), Object)
        ButtonTool73.SharedPropsInternal.AppearancesSmall.Appearance = Appearance157
        ButtonTool73.SharedPropsInternal.Caption = "Traspasos de Pallets"
        Appearance158.Image = CType(resources.GetObject("Appearance158.Image"), Object)
        ButtonTool74.SharedPropsInternal.AppearancesSmall.Appearance = Appearance158
        ButtonTool74.SharedPropsInternal.Caption = "Salida de Pallets"
        Appearance159.Image = CType(resources.GetObject("Appearance159.Image"), Object)
        ButtonTool78.SharedPropsInternal.AppearancesLarge.Appearance = Appearance159
        ButtonTool78.SharedPropsInternal.Caption = "Iniciar Sesión"
        ButtonTool78.SharedPropsInternal.DisplayStyle = Infragistics.Win.UltraWinToolbars.ToolDisplayStyle.ImageAndText
        Appearance160.Image = CType(resources.GetObject("Appearance160.Image"), Object)
        ButtonTool79.SharedPropsInternal.AppearancesLarge.Appearance = Appearance160
        ButtonTool79.SharedPropsInternal.Caption = "Editar Usuario"
        ButtonTool79.SharedPropsInternal.DisplayStyle = Infragistics.Win.UltraWinToolbars.ToolDisplayStyle.ImageAndText
        Appearance161.Image = CType(resources.GetObject("Appearance161.Image"), Object)
        ButtonTool80.SharedPropsInternal.AppearancesLarge.Appearance = Appearance161
        ButtonTool80.SharedPropsInternal.Caption = "Salir"
        ButtonTool80.SharedPropsInternal.DisplayStyle = Infragistics.Win.UltraWinToolbars.ToolDisplayStyle.ImageAndText
        Appearance162.Image = CType(resources.GetObject("Appearance162.Image"), Object)
        ButtonTool86.SharedPropsInternal.AppearancesLarge.Appearance = Appearance162
        ButtonTool86.SharedPropsInternal.Caption = "Registro de Camiones"
        Appearance163.Image = CType(resources.GetObject("Appearance163.Image"), Object)
        ButtonTool87.SharedPropsInternal.AppearancesLarge.Appearance = Appearance163
        ButtonTool87.SharedPropsInternal.Caption = "Captura de Pesos"
        Appearance164.Image = CType(resources.GetObject("Appearance164.Image"), Object)
        ButtonTool88.SharedPropsInternal.AppearancesLarge.Appearance = Appearance164
        ButtonTool88.SharedPropsInternal.Caption = "Reporte de Vuelos"
        Appearance165.Image = CType(resources.GetObject("Appearance165.Image"), Object)
        ButtonTool90.SharedPropsInternal.AppearancesLarge.Appearance = Appearance165
        ButtonTool90.SharedPropsInternal.Caption = "Entrada de Elementos"
        Appearance166.Image = CType(resources.GetObject("Appearance166.Image"), Object)
        ButtonTool93.SharedPropsInternal.AppearancesLarge.Appearance = Appearance166
        ButtonTool93.SharedPropsInternal.Caption = "Entrada"
        Appearance167.Image = CType(resources.GetObject("Appearance167.Image"), Object)
        ButtonTool94.SharedPropsInternal.AppearancesSmall.Appearance = Appearance167
        ButtonTool94.SharedPropsInternal.Caption = "Salida"
        Appearance168.Image = CType(resources.GetObject("Appearance168.Image"), Object)
        ButtonTool102.SharedPropsInternal.AppearancesLarge.Appearance = Appearance168
        Appearance169.Image = Global.SPC.My.Resources.Resources.rep_resumido
        ButtonTool102.SharedPropsInternal.AppearancesSmall.Appearance = Appearance169
        ButtonTool102.SharedPropsInternal.Caption = "Resumido"
        Appearance170.Image = CType(resources.GetObject("Appearance170.Image"), Object)
        ButtonTool103.SharedPropsInternal.AppearancesLarge.Appearance = Appearance170
        Appearance171.Image = Global.SPC.My.Resources.Resources.rep_detallado
        ButtonTool103.SharedPropsInternal.AppearancesSmall.Appearance = Appearance171
        ButtonTool103.SharedPropsInternal.Caption = "Detallado"
        Appearance172.Image = CType(resources.GetObject("Appearance172.Image"), Object)
        ButtonTool104.SharedPropsInternal.AppearancesLarge.Appearance = Appearance172
        Appearance173.Image = Global.SPC.My.Resources.Resources.rep_stock
        ButtonTool104.SharedPropsInternal.AppearancesSmall.Appearance = Appearance173
        ButtonTool104.SharedPropsInternal.Caption = "Stock de Elementos"
        Appearance174.Image = CType(resources.GetObject("Appearance174.Image"), Object)
        ButtonTool105.SharedPropsInternal.AppearancesLarge.Appearance = Appearance174
        Appearance175.Image = Global.SPC.My.Resources.Resources.rep_Inventario
        ButtonTool105.SharedPropsInternal.AppearancesSmall.Appearance = Appearance175
        ButtonTool105.SharedPropsInternal.Caption = "Inventario de Elementos"
        Appearance176.Image = CType(resources.GetObject("Appearance176.Image"), Object)
        ButtonTool106.SharedPropsInternal.AppearancesLarge.Appearance = Appearance176
        Appearance177.Image = Global.SPC.My.Resources.Resources.rep_fact
        ButtonTool106.SharedPropsInternal.AppearancesSmall.Appearance = Appearance177
        ButtonTool106.SharedPropsInternal.Caption = "Pre-facturación"
        Appearance178.Image = CType(resources.GetObject("Appearance178.Image"), Object)
        ButtonTool107.SharedPropsInternal.AppearancesLarge.Appearance = Appearance178
        ButtonTool107.SharedPropsInternal.Caption = "Decomisos"
        Appearance179.Image = CType(resources.GetObject("Appearance179.Image"), Object)
        ButtonTool108.SharedPropsInternal.AppearancesLarge.Appearance = Appearance179
        Appearance180.Image = Global.SPC.My.Resources.Resources.rep_seg
        ButtonTool108.SharedPropsInternal.AppearancesSmall.Appearance = Appearance180
        ButtonTool108.SharedPropsInternal.Caption = "Seguridad"
        Appearance181.Image = CType(resources.GetObject("Appearance181.Image"), Object)
        ButtonTool114.SharedPropsInternal.AppearancesLarge.Appearance = Appearance181
        Appearance182.Image = Global.SPC.My.Resources.Resources.agencia
        ButtonTool114.SharedPropsInternal.AppearancesSmall.Appearance = Appearance182
        ButtonTool114.SharedPropsInternal.Caption = "Agencia"
        Appearance183.Image = CType(resources.GetObject("Appearance183.Image"), Object)
        ButtonTool115.SharedPropsInternal.AppearancesLarge.Appearance = Appearance183
        Appearance184.Image = Global.SPC.My.Resources.Resources.avion
        ButtonTool115.SharedPropsInternal.AppearancesSmall.Appearance = Appearance184
        ButtonTool115.SharedPropsInternal.Caption = "Datos de Vuelo"
        Appearance185.Image = CType(resources.GetObject("Appearance185.Image"), Object)
        ButtonTool116.SharedPropsInternal.AppearancesLarge.Appearance = Appearance185
        Appearance186.Image = Global.SPC.My.Resources.Resources.destinos1
        ButtonTool116.SharedPropsInternal.AppearancesSmall.Appearance = Appearance186
        ButtonTool116.SharedPropsInternal.Caption = "Destino"
        Appearance187.Image = CType(resources.GetObject("Appearance187.Image"), Object)
        ButtonTool117.SharedPropsInternal.AppearancesLarge.Appearance = Appearance187
        ButtonTool117.SharedPropsInternal.Caption = "Historial de Elementos"
        Appearance188.Image = CType(resources.GetObject("Appearance188.Image"), Object)
        ButtonTool9.SharedPropsInternal.AppearancesSmall.Appearance = Appearance188
        ButtonTool9.SharedPropsInternal.Caption = "Posición de Elemento"
        Appearance189.Image = CType(resources.GetObject("Appearance189.Image"), Object)
        ButtonTool24.SharedPropsInternal.AppearancesSmall.Appearance = Appearance189
        ButtonTool24.SharedPropsInternal.Caption = "Tipos de Agencia"
        Appearance190.Image = CType(resources.GetObject("Appearance190.Image"), Object)
        ButtonTool119.SharedPropsInternal.AppearancesSmall.Appearance = Appearance190
        ButtonTool119.SharedPropsInternal.Caption = "Contactos"
        Appearance191.Image = CType(resources.GetObject("Appearance191.Image"), Object)
        ButtonTool121.SharedPropsInternal.AppearancesSmall.Appearance = Appearance191
        ButtonTool121.SharedPropsInternal.Caption = "Seguridad"
        ButtonTool123.SharedPropsInternal.Caption = "Otras"
        ButtonTool125.SharedPropsInternal.Caption = "Asignar Guia"
        ButtonTool126.SharedPropsInternal.Caption = "Acarreo"
        Appearance192.Image = CType(resources.GetObject("Appearance192.Image"), Object)
        ButtonTool128.SharedPropsInternal.AppearancesLarge.Appearance = Appearance192
        ButtonTool128.SharedPropsInternal.Caption = "Acarreo"
        Appearance193.Image = Global.SPC.My.Resources.Resources.entrada_elemento
        ButtonTool129.SharedPropsInternal.AppearancesSmall.Appearance = Appearance193
        ButtonTool129.SharedPropsInternal.Caption = "Pre-selección de Elemento"
        Appearance194.Image = CType(resources.GetObject("Appearance194.Image"), Object)
        ButtonTool85.SharedPropsInternal.AppearancesLarge.Appearance = Appearance194
        ButtonTool85.SharedPropsInternal.Caption = "Balanza"
        Appearance195.Image = Global.SPC.My.Resources.Resources.ComPeso
        ButtonTool133.SharedPropsInternal.AppearancesLarge.Appearance = Appearance195
        ButtonTool133.SharedPropsInternal.Caption = "Comparación del Peso del Elemento"
        Appearance196.Image = CType(resources.GetObject("Appearance196.Image"), Object)
        ButtonTool135.SharedPropsInternal.AppearancesLarge.Appearance = Appearance196
        ButtonTool135.SharedPropsInternal.Caption = "Stack de Elementos"
        Appearance197.Image = CType(resources.GetObject("Appearance197.Image"), Object)
        ButtonTool137.SharedPropsInternal.AppearancesLarge.Appearance = Appearance197
        ButtonTool137.SharedPropsInternal.Caption = "Pre-alert de Elementos"
        Appearance198.Image = CType(resources.GetObject("Appearance198.Image"), Object)
        ButtonTool139.SharedPropsInternal.AppearancesSmall.Appearance = Appearance198
        ButtonTool139.SharedPropsInternal.Caption = "Usuarios"
        Appearance199.Image = CType(resources.GetObject("Appearance199.Image"), Object)
        ButtonTool141.SharedPropsInternal.AppearancesLarge.Appearance = Appearance199
        ButtonTool141.SharedPropsInternal.Caption = "Buscar Actualizaciones"
        Appearance200.Image = CType(resources.GetObject("Appearance200.Image"), Object)
        ButtonTool145.SharedPropsInternal.AppearancesLarge.Appearance = Appearance200
        ButtonTool145.SharedPropsInternal.Caption = "Stock de Elementos (.txt)"
        Appearance201.Image = Global.SPC.My.Resources.Resources.reporte_pr_peso128x128
        ButtonTool113.SharedPropsInternal.AppearancesSmall.Appearance = Appearance201
        ButtonTool113.SharedPropsInternal.Caption = "Reporte de Producción (Solo peso)"
        Appearance202.Image = Global.SPC.My.Resources.Resources.visor_pr128x128
        ButtonTool143.SharedPropsInternal.AppearancesSmall.Appearance = Appearance202
        ButtonTool143.SharedPropsInternal.Caption = "Visor de Producción"
        ButtonTool8.SharedPropsInternal.Caption = "Material de Elementos"
        Appearance203.Image = Global.SPC.My.Resources.Resources.salida2
        ButtonTool15.SharedPropsInternal.AppearancesSmall.Appearance = Appearance203
        ButtonTool15.SharedPropsInternal.Caption = "Destinatarios"
        Appearance204.Image = Global.SPC.My.Resources.Resources.tarifa
        ButtonTool20.SharedPropsInternal.AppearancesSmall.Appearance = Appearance204
        ButtonTool20.SharedPropsInternal.Caption = "Tarifas"
        Appearance205.Image = Global.SPC.My.Resources.Resources.report_produ128x128
        ButtonTool25.SharedPropsInternal.AppearancesSmall.Appearance = Appearance205
        ButtonTool25.SharedPropsInternal.Caption = "Reporte de Producción"
        Appearance206.Image = Global.SPC.My.Resources.Resources.personal_zn_128x128
        ButtonTool40.SharedPropsInternal.AppearancesSmall.Appearance = Appearance206
        ButtonTool40.SharedPropsInternal.Caption = "Personal en Zonas"
        Appearance207.Image = Global.SPC.My.Resources.Resources.historial_zonas128x128
        ButtonTool147.SharedPropsInternal.AppearancesSmall.Appearance = Appearance207
        ButtonTool147.SharedPropsInternal.Caption = "Historial de Personal en Zonas"
        ButtonTool147.SharedPropsInternal.Visible = False
        Appearance208.Image = Global.SPC.My.Resources.Resources.Settings_icon
        ButtonTool146.SharedPropsInternal.AppearancesSmall.Appearance = Appearance208
        ButtonTool146.SharedPropsInternal.Caption = "Configuración General"
        Appearance209.Image = Global.SPC.My.Resources.Resources.user_cook
        ButtonTool151.SharedPropsInternal.AppearancesSmall.Appearance = Appearance209
        ButtonTool151.SharedPropsInternal.Caption = "Cargos"
        Appearance210.Image = Global.SPC.My.Resources.Resources.age_seguridad1
        ButtonTool153.SharedPropsInternal.AppearancesSmall.Appearance = Appearance210
        ButtonTool153.SharedPropsInternal.Caption = "Perfiles"
        Appearance211.Image = CType(resources.GetObject("Appearance211.Image"), Object)
        ButtonTool89.SharedPropsInternal.AppearancesLarge.Appearance = Appearance211
        ButtonTool89.SharedPropsInternal.Caption = "Registro de Mulas"
        Appearance212.Image = Global.SPC.My.Resources.Resources.Clock_icon
        ButtonTool66.SharedPropsInternal.AppearancesSmall.Appearance = Appearance212
        ButtonTool66.SharedPropsInternal.Caption = "Turnos"
        Appearance213.Image = Global.SPC.My.Resources.Resources.fingercheck
        ButtonTool75.SharedPropsInternal.AppearancesSmall.Appearance = Appearance213
        ButtonTool75.SharedPropsInternal.Caption = "Marcaciones de Empleados"
        Appearance214.Image = Global.SPC.My.Resources.Resources.Calendar_icon
        ButtonTool98.SharedPropsInternal.AppearancesSmall.Appearance = Appearance214
        ButtonTool98.SharedPropsInternal.Caption = "Asignar Turnos a Personal"
        Appearance215.Image = Global.SPC.My.Resources.Resources.Actions_view_calendar_day_icon
        ButtonTool101.SharedPropsInternal.AppearancesSmall.Appearance = Appearance215
        ButtonTool101.SharedPropsInternal.Caption = "Consultar Turnos Personal"
        Appearance216.Image = Global.SPC.My.Resources.Resources.Actions_im_ban_user_icon
        ButtonTool110.SharedPropsInternal.AppearancesSmall.Appearance = Appearance216
        ButtonTool110.SharedPropsInternal.Caption = "Permisos Especiales"
        Appearance229.Image = Global.SPC.My.Resources.Resources.correoPNG
        ButtonTool132.SharedPropsInternal.AppearancesSmall.Appearance = Appearance229
        ButtonTool132.SharedPropsInternal.Caption = "Correo"
        Appearance230.Image = Global.SPC.My.Resources.Resources.money
        ButtonTool155.SharedPropsInternal.AppearancesSmall.Appearance = Appearance230
        ButtonTool155.SharedPropsInternal.Caption = "Facturación"
        Appearance231.Image = Global.SPC.My.Resources.Resources.office_building_icon
        ButtonTool157.SharedPropsInternal.AppearancesSmall.Appearance = Appearance231
        ButtonTool157.SharedPropsInternal.Caption = "Agencias"
        Appearance232.Image = CType(resources.GetObject("Appearance232.Image"), Object)
        ButtonTool50.SharedPropsInternal.AppearancesLarge.Appearance = Appearance232
        ButtonTool50.SharedPropsInternal.Caption = "Aerolineas"
        Appearance233.Image = CType(resources.GetObject("Appearance233.Image"), Object)
        ButtonTool52.SharedPropsInternal.AppearancesLarge.Appearance = Appearance233
        ButtonTool52.SharedPropsInternal.Caption = "Agencias de Carga"
        Appearance234.Image = CType(resources.GetObject("Appearance234.Image"), Object)
        ButtonTool160.SharedPropsInternal.AppearancesLarge.Appearance = Appearance234
        ButtonTool160.SharedPropsInternal.Caption = "Instituciones"
        Appearance235.Image = CType(resources.GetObject("Appearance235.Image"), Object)
        ButtonTool161.SharedPropsInternal.AppearancesLarge.Appearance = Appearance235
        ButtonTool161.SharedPropsInternal.Caption = "Seguridad"
        Appearance236.Image = CType(resources.GetObject("Appearance236.Image"), Object)
        ButtonTool162.SharedPropsInternal.AppearancesLarge.Appearance = Appearance236
        ButtonTool162.SharedPropsInternal.Caption = "Servicios de Rampa"
        Appearance237.Image = CType(resources.GetObject("Appearance237.Image"), Object)
        ButtonTool163.SharedPropsInternal.AppearancesLarge.Appearance = Appearance237
        ButtonTool163.SharedPropsInternal.Caption = "Transporte"
        Appearance238.Image = CType(resources.GetObject("Appearance238.Image"), Object)
        ButtonTool165.SharedPropsInternal.AppearancesSmall.Appearance = Appearance238
        ButtonTool165.SharedPropsInternal.Caption = "Otros Proveedores"
        ButtonTool165.SharedPropsInternal.CustomizerCaption = "SPC.CYE.CYE.CPE"
        Appearance239.Image = CType(resources.GetObject("Appearance239.Image"), Object)
        ButtonTool167.SharedPropsInternal.AppearancesLarge.Appearance = Appearance239
        ButtonTool167.SharedPropsInternal.Caption = "Reporte Temperatura"
        Appearance240.Image = CType(resources.GetObject("Appearance240.Image"), Object)
        ButtonTool170.SharedPropsInternal.AppearancesLarge.Appearance = Appearance240
        ButtonTool170.SharedPropsInternal.Caption = "Clientes"
        Appearance241.Image = CType(resources.GetObject("Appearance241.Image"), Object)
        ButtonTool171.SharedPropsInternal.AppearancesLarge.Appearance = Appearance241
        ButtonTool171.SharedPropsInternal.Caption = "Servicios"
        Appearance242.Image = CType(resources.GetObject("Appearance242.Image"), Object)
        ButtonTool173.SharedPropsInternal.AppearancesLarge.Appearance = Appearance242
        ButtonTool173.SharedPropsInternal.Caption = "Periodicidad"
        Appearance243.Image = CType(resources.GetObject("Appearance243.Image"), Object)
        ButtonTool175.SharedPropsInternal.AppearancesLarge.Appearance = Appearance243
        ButtonTool175.SharedPropsInternal.Caption = "Plantilla Cliente Servicios"
        Appearance244.Image = CType(resources.GetObject("Appearance244.Image"), Object)
        ButtonTool177.SharedPropsInternal.AppearancesLarge.Appearance = Appearance244
        ButtonTool177.SharedPropsInternal.Caption = "Prefacturacion"
        Appearance245.Image = CType(resources.GetObject("Appearance245.Image"), Object)
        ButtonTool179.SharedPropsInternal.AppearancesLarge.Appearance = Appearance245
        ButtonTool179.SharedPropsInternal.Caption = "Servicios Consumido por Clientes"
        Appearance246.Image = CType(resources.GetObject("Appearance246.Image"), Object)
        ButtonTool181.SharedPropsInternal.AppearancesLarge.Appearance = Appearance246
        ButtonTool181.SharedPropsInternal.Caption = "Movimiento de Carga de un Cuarto Frio a Otro"
        Appearance11.Image = CType(resources.GetObject("Appearance11.Image"), Object)
        ButtonTool184.SharedPropsInternal.AppearancesSmall.Appearance = Appearance11
        ButtonTool184.SharedPropsInternal.Caption = "Configuracion Notificacion Temp"
        Appearance12.Image = CType(resources.GetObject("Appearance12.Image"), Object)
        ButtonTool185.SharedPropsInternal.AppearancesSmall.Appearance = Appearance12
        ButtonTool185.SharedPropsInternal.Caption = "Reporte Automatico Vuelo"
        Appearance13.Image = CType(resources.GetObject("Appearance13.Image"), Object)
        ButtonTool187.SharedPropsInternal.AppearancesLarge.Appearance = Appearance13
        ButtonTool187.SharedPropsInternal.Caption = "Reporte de Produccion 2"
        Appearance14.Image = Global.SPC.My.Resources.Resources.Gaveta
        ButtonTool191.SharedPropsInternal.AppearancesLarge.Appearance = Appearance14
        Appearance15.Image = Global.SPC.My.Resources.Resources.Gaveta
        ButtonTool191.SharedPropsInternal.AppearancesSmall.Appearance = Appearance15
        ButtonTool191.SharedPropsInternal.Caption = "Asignacion de Gavetas por Saca"
        Me.UtmMain.Tools.AddRange(New Infragistics.Win.UltraWinToolbars.ToolBase() {ButtonTool2, ButtonTool4, ButtonTool10, ButtonTool11, ButtonTool12, ButtonTool13, ButtonTool14, ComboBoxTool2, ButtonTool27, ButtonTool28, ButtonTool29, ButtonTool30, ButtonTool31, ButtonTool32, ButtonTool33, ButtonTool34, ButtonTool35, ButtonTool36, ButtonTool37, ButtonTool38, ButtonTool43, ButtonTool44, ButtonTool45, ButtonTool46, ButtonTool47, ButtonTool48, ButtonTool55, ButtonTool56, ButtonTool57, ButtonTool58, ButtonTool59, ButtonTool60, ButtonTool68, ButtonTool69, ButtonTool70, ButtonTool71, ButtonTool72, ButtonTool73, ButtonTool74, ButtonTool78, ButtonTool79, ButtonTool80, ButtonTool86, ButtonTool87, ButtonTool88, ButtonTool90, ButtonTool93, ButtonTool94, ButtonTool102, ButtonTool103, ButtonTool104, ButtonTool105, ButtonTool106, ButtonTool107, ButtonTool108, ButtonTool114, ButtonTool115, ButtonTool116, ButtonTool117, ButtonTool9, ButtonTool24, ButtonTool119, ButtonTool121, ButtonTool123, ButtonTool125, ButtonTool126, ButtonTool128, ButtonTool129, ButtonTool85, ButtonTool133, ButtonTool135, ButtonTool137, ButtonTool139, ButtonTool141, ButtonTool145, ButtonTool113, ButtonTool143, ButtonTool8, ButtonTool15, ButtonTool20, ButtonTool25, ButtonTool40, ButtonTool147, ButtonTool146, ButtonTool151, ButtonTool153, ButtonTool89, ButtonTool66, ButtonTool75, ButtonTool98, ButtonTool101, ButtonTool110, ButtonTool132, ButtonTool155, ButtonTool157, ButtonTool50, ButtonTool52, ButtonTool160, ButtonTool161, ButtonTool162, ButtonTool163, ButtonTool165, ButtonTool167, ButtonTool170, ButtonTool171, ButtonTool173, ButtonTool175, ButtonTool177, ButtonTool179, ButtonTool181, ButtonTool184, ButtonTool185, ButtonTool187, ButtonTool191})
        '
        '_frmMainSpc_Toolbars_Dock_Area_Left
        '
        Me._frmMainSpc_Toolbars_Dock_Area_Left.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping
        Me._frmMainSpc_Toolbars_Dock_Area_Left.BackColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(219, Byte), Integer), CType(CType(255, Byte), Integer))
        Me._frmMainSpc_Toolbars_Dock_Area_Left.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Left
        Me._frmMainSpc_Toolbars_Dock_Area_Left.ForeColor = System.Drawing.SystemColors.ControlText
        Me._frmMainSpc_Toolbars_Dock_Area_Left.InitialResizeAreaExtent = 4
        Me._frmMainSpc_Toolbars_Dock_Area_Left.Location = New System.Drawing.Point(0, 158)
        Me._frmMainSpc_Toolbars_Dock_Area_Left.Name = "_frmMainSpc_Toolbars_Dock_Area_Left"
        Me._frmMainSpc_Toolbars_Dock_Area_Left.Size = New System.Drawing.Size(4, 286)
        Me._frmMainSpc_Toolbars_Dock_Area_Left.ToolbarsManager = Me.UtmMain
        '
        '_frmMainSpc_Toolbars_Dock_Area_Bottom
        '
        Me._frmMainSpc_Toolbars_Dock_Area_Bottom.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping
        Me._frmMainSpc_Toolbars_Dock_Area_Bottom.BackColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(219, Byte), Integer), CType(CType(255, Byte), Integer))
        Me._frmMainSpc_Toolbars_Dock_Area_Bottom.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Bottom
        Me._frmMainSpc_Toolbars_Dock_Area_Bottom.ForeColor = System.Drawing.SystemColors.ControlText
        Me._frmMainSpc_Toolbars_Dock_Area_Bottom.Location = New System.Drawing.Point(0, 444)
        Me._frmMainSpc_Toolbars_Dock_Area_Bottom.Name = "_frmMainSpc_Toolbars_Dock_Area_Bottom"
        Me._frmMainSpc_Toolbars_Dock_Area_Bottom.Size = New System.Drawing.Size(963, 0)
        Me._frmMainSpc_Toolbars_Dock_Area_Bottom.ToolbarsManager = Me.UtmMain
        '
        '_frmMainSpc_Toolbars_Dock_Area_Top
        '
        Me._frmMainSpc_Toolbars_Dock_Area_Top.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping
        Me._frmMainSpc_Toolbars_Dock_Area_Top.BackColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(219, Byte), Integer), CType(CType(255, Byte), Integer))
        Me._frmMainSpc_Toolbars_Dock_Area_Top.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Top
        Me._frmMainSpc_Toolbars_Dock_Area_Top.ForeColor = System.Drawing.SystemColors.ControlText
        Me._frmMainSpc_Toolbars_Dock_Area_Top.Location = New System.Drawing.Point(0, 0)
        Me._frmMainSpc_Toolbars_Dock_Area_Top.Name = "_frmMainSpc_Toolbars_Dock_Area_Top"
        Me._frmMainSpc_Toolbars_Dock_Area_Top.Size = New System.Drawing.Size(963, 158)
        Me._frmMainSpc_Toolbars_Dock_Area_Top.ToolbarsManager = Me.UtmMain
        '
        'frmMainSpc
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.ClientSize = New System.Drawing.Size(963, 467)
        Me.Controls.Add(Me.pnlMain)
        Me.Controls.Add(Me._frmMainSpc_Toolbars_Dock_Area_Left)
        Me.Controls.Add(Me._frmMainSpc_Toolbars_Dock_Area_Right)
        Me.Controls.Add(Me._frmMainSpc_Toolbars_Dock_Area_Top)
        Me.Controls.Add(Me._frmMainSpc_Toolbars_Dock_Area_Bottom)
        Me.Controls.Add(Me.usbPrincipal)
        Me.Icon = CType(resources.GetObject("$this.Icon"), System.Drawing.Icon)
        Me.Name = "frmMainSpc"
        Me.Text = "SPC"
        Me.WindowState = System.Windows.Forms.FormWindowState.Maximized
        Me.pnlMain.ResumeLayout(False)
        CType(Me.usbPrincipal, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.UtmMain, System.ComponentModel.ISupportInitialize).EndInit()
        Me.ResumeLayout(False)

    End Sub
    Friend WithEvents pnlMain As Infragistics.Win.Misc.UltraPanel
    Friend WithEvents usbPrincipal As Infragistics.Win.UltraWinStatusBar.UltraStatusBar
    Friend WithEvents UtmMain As Infragistics.Win.UltraWinToolbars.UltraToolbarsManager
    Friend WithEvents _frmMainSpc_Toolbars_Dock_Area_Left As Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea
    Friend WithEvents _frmMainSpc_Toolbars_Dock_Area_Right As Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea
    Friend WithEvents _frmMainSpc_Toolbars_Dock_Area_Top As Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea
    Friend WithEvents _frmMainSpc_Toolbars_Dock_Area_Bottom As Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea
End Class
