'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace Server.CourrierService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="Server.CourrierService.CourrierServiceSoap")>  _
    Public Interface CourrierServiceSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SaveGavetaGuia", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function SaveGavetaGuia(ByVal req As Server.CourrierService.GavetaGuiaRequest) As Server.CourrierService.GavetaGuiaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SaveGavetaGuia", ReplyAction:="*")>  _
        Function SaveGavetaGuiaAsync(ByVal req As Server.CourrierService.GavetaGuiaRequest) As System.Threading.Tasks.Task(Of Server.CourrierService.GavetaGuiaResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EliminarGavetaGuia", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function EliminarGavetaGuia(ByVal req As Server.CourrierService.GavetaGuiaRequest) As Server.CourrierService.GavetaGuiaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EliminarGavetaGuia", ReplyAction:="*")>  _
        Function EliminarGavetaGuiaAsync(ByVal req As Server.CourrierService.GavetaGuiaRequest) As System.Threading.Tasks.Task(Of Server.CourrierService.GavetaGuiaResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ModificarGavetaGuia", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function ModificarGavetaGuia(ByVal req As Server.CourrierService.GavetaGuiaRequest) As Server.CourrierService.GavetaGuiaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ModificarGavetaGuia", ReplyAction:="*")>  _
        Function ModificarGavetaGuiaAsync(ByVal req As Server.CourrierService.GavetaGuiaRequest) As System.Threading.Tasks.Task(Of Server.CourrierService.GavetaGuiaResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ObtenerGavetaGuiaporBriefingIdGuia", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function ObtenerGavetaGuiaporBriefingIdGuia(ByVal req As Server.CourrierService.GavetaGuiaRequest) As Server.CourrierService.GavetaGuiaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ObtenerGavetaGuiaporBriefingIdGuia", ReplyAction:="*")>  _
        Function ObtenerGavetaGuiaporBriefingIdGuiaAsync(ByVal req As Server.CourrierService.GavetaGuiaRequest) As System.Threading.Tasks.Task(Of Server.CourrierService.GavetaGuiaResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getGavetaGuiaporIdGuiaIdElemento", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function getGavetaGuiaporIdGuiaIdElemento(ByVal req As Server.CourrierService.GavetaGuiaRequest) As Server.CourrierService.GavetaGuiaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getGavetaGuiaporIdGuiaIdElemento", ReplyAction:="*")>  _
        Function getGavetaGuiaporIdGuiaIdElementoAsync(ByVal req As Server.CourrierService.GavetaGuiaRequest) As System.Threading.Tasks.Task(Of Server.CourrierService.GavetaGuiaResponse)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GavetaGuiaRequest
        Inherits GenericRequest
        
        Private myGavetaGuiaItemField As GavetaGuiaItem
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property myGavetaGuiaItem() As GavetaGuiaItem
            Get
                Return Me.myGavetaGuiaItemField
            End Get
            Set
                Me.myGavetaGuiaItemField = value
                Me.RaisePropertyChanged("myGavetaGuiaItem")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GavetaGuiaItem
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private idgavetaguiaField As String
        
        Private idGuiaField As String
        
        Private idDetalleProcesoField As String
        
        Private idBriefingField As String
        
        Private idElementoField As String
        
        Private fechaField As Date
        
        Private pesoReferencialElementoField As Double
        
        Private fechaCargaField As Date
        
        Private pesoCargaField As Double
        
        Private estadoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property idgavetaguia() As String
            Get
                Return Me.idgavetaguiaField
            End Get
            Set
                Me.idgavetaguiaField = value
                Me.RaisePropertyChanged("idgavetaguia")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property idGuia() As String
            Get
                Return Me.idGuiaField
            End Get
            Set
                Me.idGuiaField = value
                Me.RaisePropertyChanged("idGuia")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property idDetalleProceso() As String
            Get
                Return Me.idDetalleProcesoField
            End Get
            Set
                Me.idDetalleProcesoField = value
                Me.RaisePropertyChanged("idDetalleProceso")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property idBriefing() As String
            Get
                Return Me.idBriefingField
            End Get
            Set
                Me.idBriefingField = value
                Me.RaisePropertyChanged("idBriefing")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property idElemento() As String
            Get
                Return Me.idElementoField
            End Get
            Set
                Me.idElementoField = value
                Me.RaisePropertyChanged("idElemento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property fecha() As Date
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
                Me.RaisePropertyChanged("fecha")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property pesoReferencialElemento() As Double
            Get
                Return Me.pesoReferencialElementoField
            End Get
            Set
                Me.pesoReferencialElementoField = value
                Me.RaisePropertyChanged("pesoReferencialElemento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property fechaCarga() As Date
            Get
                Return Me.fechaCargaField
            End Get
            Set
                Me.fechaCargaField = value
                Me.RaisePropertyChanged("fechaCarga")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property pesoCarga() As Double
            Get
                Return Me.pesoCargaField
            End Get
            Set
                Me.pesoCargaField = value
                Me.RaisePropertyChanged("pesoCarga")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
                Me.RaisePropertyChanged("estado")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(GavetaGuiaResponse)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GenericResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private errorCodeField As Integer
        
        Private errorMessageField As String
        
        Private actionResultField As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property ErrorCode() As Integer
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
                Me.RaisePropertyChanged("ErrorCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property ErrorMessage() As String
            Get
                Return Me.errorMessageField
            End Get
            Set
                Me.errorMessageField = value
                Me.RaisePropertyChanged("ErrorMessage")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property ActionResult() As Boolean
            Get
                Return Me.actionResultField
            End Get
            Set
                Me.actionResultField = value
                Me.RaisePropertyChanged("ActionResult")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GavetaGuiaResponse
        Inherits GenericResponse
        
        Private dsResultField As System.Data.DataSet
        
        Private myGavetaGuiaItemField As GavetaGuiaItem
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property dsResult() As System.Data.DataSet
            Get
                Return Me.dsResultField
            End Get
            Set
                Me.dsResultField = value
                Me.RaisePropertyChanged("dsResult")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property myGavetaGuiaItem() As GavetaGuiaItem
            Get
                Return Me.myGavetaGuiaItemField
            End Get
            Set
                Me.myGavetaGuiaItemField = value
                Me.RaisePropertyChanged("myGavetaGuiaItem")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(GavetaGuiaRequest)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GenericRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private ipAddressField As String
        
        Private terminalIdField As String
        
        Private actionKeyField As String
        
        Private interfaceIdField As String
        
        Private requestDateField As Date
        
        Private pcIdField As String
        
        Private userIdField As String
        
        Private myManagementActionField As ManagementActions
        
        Private sessionKeyField As System.Guid
        
        Private idField As System.Guid
        
        Private fechaIniField As Date
        
        Private fechaFinField As Date
        
        Private codigoVueloField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property IpAddress() As String
            Get
                Return Me.ipAddressField
            End Get
            Set
                Me.ipAddressField = value
                Me.RaisePropertyChanged("IpAddress")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property TerminalId() As String
            Get
                Return Me.terminalIdField
            End Get
            Set
                Me.terminalIdField = value
                Me.RaisePropertyChanged("TerminalId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property ActionKey() As String
            Get
                Return Me.actionKeyField
            End Get
            Set
                Me.actionKeyField = value
                Me.RaisePropertyChanged("ActionKey")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property InterfaceId() As String
            Get
                Return Me.interfaceIdField
            End Get
            Set
                Me.interfaceIdField = value
                Me.RaisePropertyChanged("InterfaceId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property RequestDate() As Date
            Get
                Return Me.requestDateField
            End Get
            Set
                Me.requestDateField = value
                Me.RaisePropertyChanged("RequestDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property PcId() As String
            Get
                Return Me.pcIdField
            End Get
            Set
                Me.pcIdField = value
                Me.RaisePropertyChanged("PcId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property UserId() As String
            Get
                Return Me.userIdField
            End Get
            Set
                Me.userIdField = value
                Me.RaisePropertyChanged("UserId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property myManagementAction() As ManagementActions
            Get
                Return Me.myManagementActionField
            End Get
            Set
                Me.myManagementActionField = value
                Me.RaisePropertyChanged("myManagementAction")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property SessionKey() As System.Guid
            Get
                Return Me.sessionKeyField
            End Get
            Set
                Me.sessionKeyField = value
                Me.RaisePropertyChanged("SessionKey")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property id() As System.Guid
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
                Me.RaisePropertyChanged("id")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property fechaIni() As Date
            Get
                Return Me.fechaIniField
            End Get
            Set
                Me.fechaIniField = value
                Me.RaisePropertyChanged("fechaIni")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property fechaFin() As Date
            Get
                Return Me.fechaFinField
            End Get
            Set
                Me.fechaFinField = value
                Me.RaisePropertyChanged("fechaFin")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=12)>  _
        Public Property codigoVuelo() As String
            Get
                Return Me.codigoVueloField
            End Get
            Set
                Me.codigoVueloField = value
                Me.RaisePropertyChanged("codigoVuelo")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum ManagementActions
        
        '''<remarks/>
        [NOTHING]
        
        '''<remarks/>
        INSERT
        
        '''<remarks/>
        UPDATE
        
        '''<remarks/>
        DELETE
        
        '''<remarks/>
        QUERY
        
        '''<remarks/>
        REPLICATED
        
        '''<remarks/>
        REFRESH
        
        '''<remarks/>
        EXPORT
        
        '''<remarks/>
        SEARCH
        
        '''<remarks/>
        PRINT
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface CourrierServiceSoapChannel
        Inherits Server.CourrierService.CourrierServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CourrierServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of Server.CourrierService.CourrierServiceSoap)
        Implements Server.CourrierService.CourrierServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function SaveGavetaGuia(ByVal req As Server.CourrierService.GavetaGuiaRequest) As Server.CourrierService.GavetaGuiaResponse Implements Server.CourrierService.CourrierServiceSoap.SaveGavetaGuia
            Return MyBase.Channel.SaveGavetaGuia(req)
        End Function
        
        Public Function SaveGavetaGuiaAsync(ByVal req As Server.CourrierService.GavetaGuiaRequest) As System.Threading.Tasks.Task(Of Server.CourrierService.GavetaGuiaResponse) Implements Server.CourrierService.CourrierServiceSoap.SaveGavetaGuiaAsync
            Return MyBase.Channel.SaveGavetaGuiaAsync(req)
        End Function
        
        Public Function EliminarGavetaGuia(ByVal req As Server.CourrierService.GavetaGuiaRequest) As Server.CourrierService.GavetaGuiaResponse Implements Server.CourrierService.CourrierServiceSoap.EliminarGavetaGuia
            Return MyBase.Channel.EliminarGavetaGuia(req)
        End Function
        
        Public Function EliminarGavetaGuiaAsync(ByVal req As Server.CourrierService.GavetaGuiaRequest) As System.Threading.Tasks.Task(Of Server.CourrierService.GavetaGuiaResponse) Implements Server.CourrierService.CourrierServiceSoap.EliminarGavetaGuiaAsync
            Return MyBase.Channel.EliminarGavetaGuiaAsync(req)
        End Function
        
        Public Function ModificarGavetaGuia(ByVal req As Server.CourrierService.GavetaGuiaRequest) As Server.CourrierService.GavetaGuiaResponse Implements Server.CourrierService.CourrierServiceSoap.ModificarGavetaGuia
            Return MyBase.Channel.ModificarGavetaGuia(req)
        End Function
        
        Public Function ModificarGavetaGuiaAsync(ByVal req As Server.CourrierService.GavetaGuiaRequest) As System.Threading.Tasks.Task(Of Server.CourrierService.GavetaGuiaResponse) Implements Server.CourrierService.CourrierServiceSoap.ModificarGavetaGuiaAsync
            Return MyBase.Channel.ModificarGavetaGuiaAsync(req)
        End Function
        
        Public Function ObtenerGavetaGuiaporBriefingIdGuia(ByVal req As Server.CourrierService.GavetaGuiaRequest) As Server.CourrierService.GavetaGuiaResponse Implements Server.CourrierService.CourrierServiceSoap.ObtenerGavetaGuiaporBriefingIdGuia
            Return MyBase.Channel.ObtenerGavetaGuiaporBriefingIdGuia(req)
        End Function
        
        Public Function ObtenerGavetaGuiaporBriefingIdGuiaAsync(ByVal req As Server.CourrierService.GavetaGuiaRequest) As System.Threading.Tasks.Task(Of Server.CourrierService.GavetaGuiaResponse) Implements Server.CourrierService.CourrierServiceSoap.ObtenerGavetaGuiaporBriefingIdGuiaAsync
            Return MyBase.Channel.ObtenerGavetaGuiaporBriefingIdGuiaAsync(req)
        End Function
        
        Public Function getGavetaGuiaporIdGuiaIdElemento(ByVal req As Server.CourrierService.GavetaGuiaRequest) As Server.CourrierService.GavetaGuiaResponse Implements Server.CourrierService.CourrierServiceSoap.getGavetaGuiaporIdGuiaIdElemento
            Return MyBase.Channel.getGavetaGuiaporIdGuiaIdElemento(req)
        End Function
        
        Public Function getGavetaGuiaporIdGuiaIdElementoAsync(ByVal req As Server.CourrierService.GavetaGuiaRequest) As System.Threading.Tasks.Task(Of Server.CourrierService.GavetaGuiaResponse) Implements Server.CourrierService.CourrierServiceSoap.getGavetaGuiaporIdGuiaIdElementoAsync
            Return MyBase.Channel.getGavetaGuiaporIdGuiaIdElementoAsync(req)
        End Function
    End Class
End Namespace
