'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace Server.SyncService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://espc.org/", ConfigurationName:="Server.SyncService.SyncServiceSoap")>  _
    Public Interface SyncServiceSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://espc.org/GetServerLastUpdate", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function GetServerLastUpdate(ByVal req As Server.SyncService.SyncRequest) As Server.SyncService.SyncResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://espc.org/GetServerLastUpdate", ReplyAction:="*")>  _
        Function GetServerLastUpdateAsync(ByVal req As Server.SyncService.SyncRequest) As System.Threading.Tasks.Task(Of Server.SyncService.SyncResponse)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://espc.org/")>  _
    Partial Public Class SyncRequest
        Inherits GenericRequest
        
        Private clientVersionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property ClientVersion() As String
            Get
                Return Me.clientVersionField
            End Get
            Set
                Me.clientVersionField = value
                Me.RaisePropertyChanged("ClientVersion")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(SyncRequest)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://espc.org/")>  _
    Partial Public Class GenericRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private ipAddressField As String
        
        Private terminalIdField As String
        
        Private actionKeyField As String
        
        Private interfaceIdField As String
        
        Private requestDateField As Date
        
        Private pcIdField As String
        
        Private userIdField As String
        
        Private myManagementActionField As ManagementActions
        
        Private sessionKeyField As System.Guid
        
        Private idField As System.Guid
        
        Private fechaIniField As Date
        
        Private fechaFinField As Date
        
        Private codigoVueloField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property IpAddress() As String
            Get
                Return Me.ipAddressField
            End Get
            Set
                Me.ipAddressField = value
                Me.RaisePropertyChanged("IpAddress")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property TerminalId() As String
            Get
                Return Me.terminalIdField
            End Get
            Set
                Me.terminalIdField = value
                Me.RaisePropertyChanged("TerminalId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property ActionKey() As String
            Get
                Return Me.actionKeyField
            End Get
            Set
                Me.actionKeyField = value
                Me.RaisePropertyChanged("ActionKey")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property InterfaceId() As String
            Get
                Return Me.interfaceIdField
            End Get
            Set
                Me.interfaceIdField = value
                Me.RaisePropertyChanged("InterfaceId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property RequestDate() As Date
            Get
                Return Me.requestDateField
            End Get
            Set
                Me.requestDateField = value
                Me.RaisePropertyChanged("RequestDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property PcId() As String
            Get
                Return Me.pcIdField
            End Get
            Set
                Me.pcIdField = value
                Me.RaisePropertyChanged("PcId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property UserId() As String
            Get
                Return Me.userIdField
            End Get
            Set
                Me.userIdField = value
                Me.RaisePropertyChanged("UserId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property myManagementAction() As ManagementActions
            Get
                Return Me.myManagementActionField
            End Get
            Set
                Me.myManagementActionField = value
                Me.RaisePropertyChanged("myManagementAction")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property SessionKey() As System.Guid
            Get
                Return Me.sessionKeyField
            End Get
            Set
                Me.sessionKeyField = value
                Me.RaisePropertyChanged("SessionKey")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property id() As System.Guid
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
                Me.RaisePropertyChanged("id")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property fechaIni() As Date
            Get
                Return Me.fechaIniField
            End Get
            Set
                Me.fechaIniField = value
                Me.RaisePropertyChanged("fechaIni")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property fechaFin() As Date
            Get
                Return Me.fechaFinField
            End Get
            Set
                Me.fechaFinField = value
                Me.RaisePropertyChanged("fechaFin")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=12)>  _
        Public Property codigoVuelo() As String
            Get
                Return Me.codigoVueloField
            End Get
            Set
                Me.codigoVueloField = value
                Me.RaisePropertyChanged("codigoVuelo")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://espc.org/")>  _
    Public Enum ManagementActions
        
        '''<remarks/>
        [NOTHING]
        
        '''<remarks/>
        INSERT
        
        '''<remarks/>
        UPDATE
        
        '''<remarks/>
        DELETE
        
        '''<remarks/>
        QUERY
        
        '''<remarks/>
        REPLICATED
        
        '''<remarks/>
        REFRESH
        
        '''<remarks/>
        EXPORT
        
        '''<remarks/>
        SEARCH
        
        '''<remarks/>
        PRINT
    End Enum
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(SyncResponse)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://espc.org/")>  _
    Partial Public Class GenericResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private errorCodeField As Integer
        
        Private errorMessageField As String
        
        Private actionResultField As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property ErrorCode() As Integer
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
                Me.RaisePropertyChanged("ErrorCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property ErrorMessage() As String
            Get
                Return Me.errorMessageField
            End Get
            Set
                Me.errorMessageField = value
                Me.RaisePropertyChanged("ErrorMessage")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property ActionResult() As Boolean
            Get
                Return Me.actionResultField
            End Get
            Set
                Me.actionResultField = value
                Me.RaisePropertyChanged("ActionResult")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://espc.org/")>  _
    Partial Public Class SyncResponse
        Inherits GenericResponse
        
        Private serverLastUpdateField As Date
        
        Private dsResultField As System.Data.DataSet
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property ServerLastUpdate() As Date
            Get
                Return Me.serverLastUpdateField
            End Get
            Set
                Me.serverLastUpdateField = value
                Me.RaisePropertyChanged("ServerLastUpdate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property dsResult() As System.Data.DataSet
            Get
                Return Me.dsResultField
            End Get
            Set
                Me.dsResultField = value
                Me.RaisePropertyChanged("dsResult")
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface SyncServiceSoapChannel
        Inherits Server.SyncService.SyncServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SyncServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of Server.SyncService.SyncServiceSoap)
        Implements Server.SyncService.SyncServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetServerLastUpdate(ByVal req As Server.SyncService.SyncRequest) As Server.SyncService.SyncResponse Implements Server.SyncService.SyncServiceSoap.GetServerLastUpdate
            Return MyBase.Channel.GetServerLastUpdate(req)
        End Function
        
        Public Function GetServerLastUpdateAsync(ByVal req As Server.SyncService.SyncRequest) As System.Threading.Tasks.Task(Of Server.SyncService.SyncResponse) Implements Server.SyncService.SyncServiceSoap.GetServerLastUpdateAsync
            Return MyBase.Channel.GetServerLastUpdateAsync(req)
        End Function
    End Class
End Namespace
