'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace Server.Facturacion
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="Server.Facturacion.FacturacionSoap")>  _
    Public Interface FacturacionSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/MantClientes", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function MantClientes(ByVal req As Server.Facturacion.ClienteRequest) As Server.Facturacion.ClienteResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/MantClientes", ReplyAction:="*")>  _
        Function MantClientesAsync(ByVal req As Server.Facturacion.ClienteRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.ClienteResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/MantServiciosGA", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function MantServiciosGA(ByVal req As Server.Facturacion.ServiciosGARequest) As Server.Facturacion.ServiciosGAResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/MantServiciosGA", ReplyAction:="*")>  _
        Function MantServiciosGAAsync(ByVal req As Server.Facturacion.ServiciosGARequest) As System.Threading.Tasks.Task(Of Server.Facturacion.ServiciosGAResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/MantPlantiClienteServ", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function MantPlantiClienteServ(ByVal req As Server.Facturacion.PlantillaClienServRequest) As Server.Facturacion.PlantillaClienServResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/MantPlantiClienteServ", ReplyAction:="*")>  _
        Function MantPlantiClienteServAsync(ByVal req As Server.Facturacion.PlantillaClienServRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.PlantillaClienServResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/MantPeriodicidad", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function MantPeriodicidad(ByVal req As Server.Facturacion.PeriodicidadRequest) As Server.Facturacion.PeriodicidadResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/MantPeriodicidad", ReplyAction:="*")>  _
        Function MantPeriodicidadAsync(ByVal req As Server.Facturacion.PeriodicidadRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.PeriodicidadResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/MantServConsuCliente", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function MantServConsuCliente(ByVal req As Server.Facturacion.ServConsuClienteRequest) As Server.Facturacion.ServConsuClienteResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/MantServConsuCliente", ReplyAction:="*")>  _
        Function MantServConsuClienteAsync(ByVal req As Server.Facturacion.ServConsuClienteRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.ServConsuClienteResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/MantVuelosCancelados", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function MantVuelosCancelados(ByVal req As Server.Facturacion.VuelosCanceladosRequest) As Server.Facturacion.VuelosCanceladosResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/MantVuelosCancelados", ReplyAction:="*")>  _
        Function MantVuelosCanceladosAsync(ByVal req As Server.Facturacion.VuelosCanceladosRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.VuelosCanceladosResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetClientes", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function GetClientes(ByVal req As Server.Facturacion.ClienteRequest) As Server.Facturacion.ClienteResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetClientes", ReplyAction:="*")>  _
        Function GetClientesAsync(ByVal req As Server.Facturacion.ClienteRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.ClienteResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetServiciosGA", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function GetServiciosGA(ByVal req As Server.Facturacion.ServiciosGARequest) As Server.Facturacion.ServiciosGAResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetServiciosGA", ReplyAction:="*")>  _
        Function GetServiciosGAAsync(ByVal req As Server.Facturacion.ServiciosGARequest) As System.Threading.Tasks.Task(Of Server.Facturacion.ServiciosGAResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetPeriodicidad", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function GetPeriodicidad(ByVal req As Server.Facturacion.PeriodicidadRequest) As Server.Facturacion.PeriodicidadResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetPeriodicidad", ReplyAction:="*")>  _
        Function GetPeriodicidadAsync(ByVal req As Server.Facturacion.PeriodicidadRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.PeriodicidadResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetPlantiClienteServ", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function GetPlantiClienteServ(ByVal req As Server.Facturacion.PlantillaClienServRequest) As Server.Facturacion.PlantillaClienServResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetPlantiClienteServ", ReplyAction:="*")>  _
        Function GetPlantiClienteServAsync(ByVal req As Server.Facturacion.PlantillaClienServRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.PlantillaClienServResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetTipoProceAlmacenaCarga", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function GetTipoProceAlmacenaCarga(ByVal req As Server.Facturacion.TipoProcesoAlmacenajeCargaRequest) As Server.Facturacion.TipoProcesoAlmacenajeCargaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetTipoProceAlmacenaCarga", ReplyAction:="*")>  _
        Function GetTipoProceAlmacenaCargaAsync(ByVal req As Server.Facturacion.TipoProcesoAlmacenajeCargaRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.TipoProcesoAlmacenajeCargaResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PreFactObtenerPesoVolumenVuelo", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function PreFactObtenerPesoVolumenVuelo(ByVal req As Server.Facturacion.PlantillaClienServRequest) As Server.Facturacion.PlantillaClienServResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PreFactObtenerPesoVolumenVuelo", ReplyAction:="*")>  _
        Function PreFactObtenerPesoVolumenVueloAsync(ByVal req As Server.Facturacion.PlantillaClienServRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.PlantillaClienServResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PreFactObtenerCantVuelosAgencia", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function PreFactObtenerCantVuelosAgencia(ByVal req As Server.Facturacion.PlantillaClienServRequest) As Server.Facturacion.PlantillaClienServResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PreFactObtenerCantVuelosAgencia", ReplyAction:="*")>  _
        Function PreFactObtenerCantVuelosAgenciaAsync(ByVal req As Server.Facturacion.PlantillaClienServRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.PlantillaClienServResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PreFactObtenerPesoVolumenGuia", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function PreFactObtenerPesoVolumenGuia(ByVal req As Server.Facturacion.PlantillaClienServRequest) As Server.Facturacion.PlantillaClienServResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PreFactObtenerPesoVolumenGuia", ReplyAction:="*")>  _
        Function PreFactObtenerPesoVolumenGuiaAsync(ByVal req As Server.Facturacion.PlantillaClienServRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.PlantillaClienServResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PreFactObtenerTiempoAlmaceContainer", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function PreFactObtenerTiempoAlmaceContainer(ByVal req As Server.Facturacion.PlantillaClienServRequest) As Server.Facturacion.PlantillaClienServResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PreFactObtenerTiempoAlmaceContainer", ReplyAction:="*")>  _
        Function PreFactObtenerTiempoAlmaceContainerAsync(ByVal req As Server.Facturacion.PlantillaClienServRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.PlantillaClienServResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetSerConsuCliente", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function GetSerConsuCliente(ByVal req As Server.Facturacion.ServConsuClienteRequest) As Server.Facturacion.ServConsuClienteResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetSerConsuCliente", ReplyAction:="*")>  _
        Function GetSerConsuClienteAsync(ByVal req As Server.Facturacion.ServConsuClienteRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.ServConsuClienteResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetVuelosCancelados", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function GetVuelosCancelados(ByVal req As Server.Facturacion.VuelosCanceladosRequest) As Server.Facturacion.VuelosCanceladosResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetVuelosCancelados", ReplyAction:="*")>  _
        Function GetVuelosCanceladosAsync(ByVal req As Server.Facturacion.VuelosCanceladosRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.VuelosCanceladosResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetVuelosGuias", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function GetVuelosGuias(ByVal req As Server.Facturacion.VuelosCanceladosRequest) As Server.Facturacion.VuelosCanceladosResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetVuelosGuias", ReplyAction:="*")>  _
        Function GetVuelosGuiasAsync(ByVal req As Server.Facturacion.VuelosCanceladosRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.VuelosCanceladosResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PreFactObtenerServConsuCliente", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function PreFactObtenerServConsuCliente(ByVal req As Server.Facturacion.ServConsuClienteRequest) As Server.Facturacion.ServConsuClienteResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PreFactObtenerServConsuCliente", ReplyAction:="*")>  _
        Function PreFactObtenerServConsuClienteAsync(ByVal req As Server.Facturacion.ServConsuClienteRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.ServConsuClienteResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PreFactObtenerPesoVolumenPorBriefGuia", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function PreFactObtenerPesoVolumenPorBriefGuia(ByVal req As Server.Facturacion.ServConsuClienteRequest) As Server.Facturacion.ServConsuClienteResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PreFactObtenerPesoVolumenPorBriefGuia", ReplyAction:="*")>  _
        Function PreFactObtenerPesoVolumenPorBriefGuiaAsync(ByVal req As Server.Facturacion.ServConsuClienteRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.ServConsuClienteResponse)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ClienteRequest
        Inherits GenericRequest
        
        Private clienteField As Cliente
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Cliente() As Cliente
            Get
                Return Me.clienteField
            End Get
            Set
                Me.clienteField = value
                Me.RaisePropertyChanged("Cliente")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Cliente
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private idClienteField As Integer
        
        Private idAgenciaField As System.Guid
        
        Private estadoField As String
        
        Private fechaIngresoField As Date
        
        Private usuarioIngresoField As String
        
        Private fechaActualizacionField As Date
        
        Private usuarioActualizacionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property idCliente() As Integer
            Get
                Return Me.idClienteField
            End Get
            Set
                Me.idClienteField = value
                Me.RaisePropertyChanged("idCliente")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property idAgencia() As System.Guid
            Get
                Return Me.idAgenciaField
            End Get
            Set
                Me.idAgenciaField = value
                Me.RaisePropertyChanged("idAgencia")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
                Me.RaisePropertyChanged("Estado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property FechaIngreso() As Date
            Get
                Return Me.fechaIngresoField
            End Get
            Set
                Me.fechaIngresoField = value
                Me.RaisePropertyChanged("FechaIngreso")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property UsuarioIngreso() As String
            Get
                Return Me.usuarioIngresoField
            End Get
            Set
                Me.usuarioIngresoField = value
                Me.RaisePropertyChanged("UsuarioIngreso")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property FechaActualizacion() As Date
            Get
                Return Me.fechaActualizacionField
            End Get
            Set
                Me.fechaActualizacionField = value
                Me.RaisePropertyChanged("FechaActualizacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property UsuarioActualizacion() As String
            Get
                Return Me.usuarioActualizacionField
            End Get
            Set
                Me.usuarioActualizacionField = value
                Me.RaisePropertyChanged("UsuarioActualizacion")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(TipoProcesoAlmacenajeCargaResponse)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(VuelosCanceladosResponse)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ServConsuClienteResponse)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(PeriodicidadResponse)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(PlantillaClienServResponse)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ServiciosGAResponse)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ClienteResponse)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GenericResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private errorCodeField As Integer
        
        Private errorMessageField As String
        
        Private actionResultField As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property ErrorCode() As Integer
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
                Me.RaisePropertyChanged("ErrorCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property ErrorMessage() As String
            Get
                Return Me.errorMessageField
            End Get
            Set
                Me.errorMessageField = value
                Me.RaisePropertyChanged("ErrorMessage")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property ActionResult() As Boolean
            Get
                Return Me.actionResultField
            End Get
            Set
                Me.actionResultField = value
                Me.RaisePropertyChanged("ActionResult")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class TipoProcesoAlmacenajeCargaResponse
        Inherits GenericResponse
        
        Private dsResultField As System.Data.DataSet
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property dsResult() As System.Data.DataSet
            Get
                Return Me.dsResultField
            End Get
            Set
                Me.dsResultField = value
                Me.RaisePropertyChanged("dsResult")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class VuelosCanceladosResponse
        Inherits GenericResponse
        
        Private dsResultField As System.Data.DataSet
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property dsResult() As System.Data.DataSet
            Get
                Return Me.dsResultField
            End Get
            Set
                Me.dsResultField = value
                Me.RaisePropertyChanged("dsResult")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ServConsuClienteResponse
        Inherits GenericResponse
        
        Private dsResultField As System.Data.DataSet
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property dsResult() As System.Data.DataSet
            Get
                Return Me.dsResultField
            End Get
            Set
                Me.dsResultField = value
                Me.RaisePropertyChanged("dsResult")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class PeriodicidadResponse
        Inherits GenericResponse
        
        Private dsResultField As System.Data.DataSet
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property dsResult() As System.Data.DataSet
            Get
                Return Me.dsResultField
            End Get
            Set
                Me.dsResultField = value
                Me.RaisePropertyChanged("dsResult")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class PlantillaClienServResponse
        Inherits GenericResponse
        
        Private dsResultField As System.Data.DataSet
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property dsResult() As System.Data.DataSet
            Get
                Return Me.dsResultField
            End Get
            Set
                Me.dsResultField = value
                Me.RaisePropertyChanged("dsResult")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ServiciosGAResponse
        Inherits GenericResponse
        
        Private dsResultField As System.Data.DataSet
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property dsResult() As System.Data.DataSet
            Get
                Return Me.dsResultField
            End Get
            Set
                Me.dsResultField = value
                Me.RaisePropertyChanged("dsResult")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ClienteResponse
        Inherits GenericResponse
        
        Private dsResultField As System.Data.DataSet
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property dsResult() As System.Data.DataSet
            Get
                Return Me.dsResultField
            End Get
            Set
                Me.dsResultField = value
                Me.RaisePropertyChanged("dsResult")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class TipoProcesoAlmacenajeCarga
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private idTipoProcAlmaCargField As Integer
        
        Private descripcionTipoProcAlmaCargField As String
        
        Private valorProcAlmaCargField As String
        
        Private estadoField As String
        
        Private fechaIngresoField As Date
        
        Private usuarioIngresoField As String
        
        Private fechaActualizacionField As Date
        
        Private usuarioActualizacionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property IdTipoProcAlmaCarg() As Integer
            Get
                Return Me.idTipoProcAlmaCargField
            End Get
            Set
                Me.idTipoProcAlmaCargField = value
                Me.RaisePropertyChanged("IdTipoProcAlmaCarg")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property DescripcionTipoProcAlmaCarg() As String
            Get
                Return Me.descripcionTipoProcAlmaCargField
            End Get
            Set
                Me.descripcionTipoProcAlmaCargField = value
                Me.RaisePropertyChanged("DescripcionTipoProcAlmaCarg")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property ValorProcAlmaCarg() As String
            Get
                Return Me.valorProcAlmaCargField
            End Get
            Set
                Me.valorProcAlmaCargField = value
                Me.RaisePropertyChanged("ValorProcAlmaCarg")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property Estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
                Me.RaisePropertyChanged("Estado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property FechaIngreso() As Date
            Get
                Return Me.fechaIngresoField
            End Get
            Set
                Me.fechaIngresoField = value
                Me.RaisePropertyChanged("FechaIngreso")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property UsuarioIngreso() As String
            Get
                Return Me.usuarioIngresoField
            End Get
            Set
                Me.usuarioIngresoField = value
                Me.RaisePropertyChanged("UsuarioIngreso")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property FechaActualizacion() As Date
            Get
                Return Me.fechaActualizacionField
            End Get
            Set
                Me.fechaActualizacionField = value
                Me.RaisePropertyChanged("FechaActualizacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property UsuarioActualizacion() As String
            Get
                Return Me.usuarioActualizacionField
            End Get
            Set
                Me.usuarioActualizacionField = value
                Me.RaisePropertyChanged("UsuarioActualizacion")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class VuelosCancelados
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private idVuelosCanceladosField As Integer
        
        Private idClienteField As Integer
        
        Private idBriefingField As System.Guid
        
        Private observacionField As String
        
        Private estadoField As String
        
        Private fechaIngresoField As Date
        
        Private usuarioIngresoField As String
        
        Private fechaActualizacionField As Date
        
        Private usuarioActualizacionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property idVuelosCancelados() As Integer
            Get
                Return Me.idVuelosCanceladosField
            End Get
            Set
                Me.idVuelosCanceladosField = value
                Me.RaisePropertyChanged("idVuelosCancelados")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property idCliente() As Integer
            Get
                Return Me.idClienteField
            End Get
            Set
                Me.idClienteField = value
                Me.RaisePropertyChanged("idCliente")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property idBriefing() As System.Guid
            Get
                Return Me.idBriefingField
            End Get
            Set
                Me.idBriefingField = value
                Me.RaisePropertyChanged("idBriefing")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property Observacion() As String
            Get
                Return Me.observacionField
            End Get
            Set
                Me.observacionField = value
                Me.RaisePropertyChanged("Observacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property Estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
                Me.RaisePropertyChanged("Estado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property FechaIngreso() As Date
            Get
                Return Me.fechaIngresoField
            End Get
            Set
                Me.fechaIngresoField = value
                Me.RaisePropertyChanged("FechaIngreso")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property UsuarioIngreso() As String
            Get
                Return Me.usuarioIngresoField
            End Get
            Set
                Me.usuarioIngresoField = value
                Me.RaisePropertyChanged("UsuarioIngreso")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property FechaActualizacion() As Date
            Get
                Return Me.fechaActualizacionField
            End Get
            Set
                Me.fechaActualizacionField = value
                Me.RaisePropertyChanged("FechaActualizacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property UsuarioActualizacion() As String
            Get
                Return Me.usuarioActualizacionField
            End Get
            Set
                Me.usuarioActualizacionField = value
                Me.RaisePropertyChanged("UsuarioActualizacion")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ServConsuCliente
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private idServConsuClienteField As Integer
        
        Private idClienteField As Integer
        
        Private idServiciosGAField As Integer
        
        Private idBriefingField As System.Guid
        
        Private idGuiaField As System.Guid
        
        Private guiaField As String
        
        Private fechaInicioField As Date
        
        Private fechaFinField As Date
        
        Private estadoField As String
        
        Private fechaIngresoField As Date
        
        Private usuarioIngresoField As String
        
        Private fechaActualizacionField As Date
        
        Private usuarioActualizacionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property idServConsuCliente() As Integer
            Get
                Return Me.idServConsuClienteField
            End Get
            Set
                Me.idServConsuClienteField = value
                Me.RaisePropertyChanged("idServConsuCliente")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property idCliente() As Integer
            Get
                Return Me.idClienteField
            End Get
            Set
                Me.idClienteField = value
                Me.RaisePropertyChanged("idCliente")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property idServiciosGA() As Integer
            Get
                Return Me.idServiciosGAField
            End Get
            Set
                Me.idServiciosGAField = value
                Me.RaisePropertyChanged("idServiciosGA")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property idBriefing() As System.Guid
            Get
                Return Me.idBriefingField
            End Get
            Set
                Me.idBriefingField = value
                Me.RaisePropertyChanged("idBriefing")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property idGuia() As System.Guid
            Get
                Return Me.idGuiaField
            End Get
            Set
                Me.idGuiaField = value
                Me.RaisePropertyChanged("idGuia")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property Guia() As String
            Get
                Return Me.guiaField
            End Get
            Set
                Me.guiaField = value
                Me.RaisePropertyChanged("Guia")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property FechaInicio() As Date
            Get
                Return Me.fechaInicioField
            End Get
            Set
                Me.fechaInicioField = value
                Me.RaisePropertyChanged("FechaInicio")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property FechaFin() As Date
            Get
                Return Me.fechaFinField
            End Get
            Set
                Me.fechaFinField = value
                Me.RaisePropertyChanged("FechaFin")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property Estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
                Me.RaisePropertyChanged("Estado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property FechaIngreso() As Date
            Get
                Return Me.fechaIngresoField
            End Get
            Set
                Me.fechaIngresoField = value
                Me.RaisePropertyChanged("FechaIngreso")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property UsuarioIngreso() As String
            Get
                Return Me.usuarioIngresoField
            End Get
            Set
                Me.usuarioIngresoField = value
                Me.RaisePropertyChanged("UsuarioIngreso")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property FechaActualizacion() As Date
            Get
                Return Me.fechaActualizacionField
            End Get
            Set
                Me.fechaActualizacionField = value
                Me.RaisePropertyChanged("FechaActualizacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=12)>  _
        Public Property UsuarioActualizacion() As String
            Get
                Return Me.usuarioActualizacionField
            End Get
            Set
                Me.usuarioActualizacionField = value
                Me.RaisePropertyChanged("UsuarioActualizacion")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Periodicidad
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private idPeriodicidadField As Integer
        
        Private descripcionPeriodicidadField As String
        
        Private estadoField As String
        
        Private fechaIngresoField As Date
        
        Private usuarioIngresoField As String
        
        Private fechaActualizacionField As Date
        
        Private usuarioActualizacionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property idPeriodicidad() As Integer
            Get
                Return Me.idPeriodicidadField
            End Get
            Set
                Me.idPeriodicidadField = value
                Me.RaisePropertyChanged("idPeriodicidad")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property DescripcionPeriodicidad() As String
            Get
                Return Me.descripcionPeriodicidadField
            End Get
            Set
                Me.descripcionPeriodicidadField = value
                Me.RaisePropertyChanged("DescripcionPeriodicidad")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
                Me.RaisePropertyChanged("Estado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property FechaIngreso() As Date
            Get
                Return Me.fechaIngresoField
            End Get
            Set
                Me.fechaIngresoField = value
                Me.RaisePropertyChanged("FechaIngreso")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property UsuarioIngreso() As String
            Get
                Return Me.usuarioIngresoField
            End Get
            Set
                Me.usuarioIngresoField = value
                Me.RaisePropertyChanged("UsuarioIngreso")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property FechaActualizacion() As Date
            Get
                Return Me.fechaActualizacionField
            End Get
            Set
                Me.fechaActualizacionField = value
                Me.RaisePropertyChanged("FechaActualizacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property UsuarioActualizacion() As String
            Get
                Return Me.usuarioActualizacionField
            End Get
            Set
                Me.usuarioActualizacionField = value
                Me.RaisePropertyChanged("UsuarioActualizacion")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class PlantillaClienServ
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private idPlantillaClienteServicioField As Integer
        
        Private idClienteField As Integer
        
        Private idServiciosGAField As Integer
        
        Private idPeriodicidadField As Integer
        
        Private valorPeriodicidadField As Integer
        
        Private valorTarifaField As Double
        
        Private cantAlmaContainerPerField As String
        
        Private idComparacionServicioField As Integer
        
        Private estadoField As String
        
        Private fechaIngresoField As Date
        
        Private usuarioIngresoField As String
        
        Private fechaActualizacionField As Date
        
        Private usuarioActualizacionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property idPlantillaClienteServicio() As Integer
            Get
                Return Me.idPlantillaClienteServicioField
            End Get
            Set
                Me.idPlantillaClienteServicioField = value
                Me.RaisePropertyChanged("idPlantillaClienteServicio")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property IdCliente() As Integer
            Get
                Return Me.idClienteField
            End Get
            Set
                Me.idClienteField = value
                Me.RaisePropertyChanged("IdCliente")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property idServiciosGA() As Integer
            Get
                Return Me.idServiciosGAField
            End Get
            Set
                Me.idServiciosGAField = value
                Me.RaisePropertyChanged("idServiciosGA")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property idPeriodicidad() As Integer
            Get
                Return Me.idPeriodicidadField
            End Get
            Set
                Me.idPeriodicidadField = value
                Me.RaisePropertyChanged("idPeriodicidad")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property ValorPeriodicidad() As Integer
            Get
                Return Me.valorPeriodicidadField
            End Get
            Set
                Me.valorPeriodicidadField = value
                Me.RaisePropertyChanged("ValorPeriodicidad")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property ValorTarifa() As Double
            Get
                Return Me.valorTarifaField
            End Get
            Set
                Me.valorTarifaField = value
                Me.RaisePropertyChanged("ValorTarifa")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property CantAlmaContainerPer() As String
            Get
                Return Me.cantAlmaContainerPerField
            End Get
            Set
                Me.cantAlmaContainerPerField = value
                Me.RaisePropertyChanged("CantAlmaContainerPer")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property IdComparacionServicio() As Integer
            Get
                Return Me.idComparacionServicioField
            End Get
            Set
                Me.idComparacionServicioField = value
                Me.RaisePropertyChanged("IdComparacionServicio")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property Estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
                Me.RaisePropertyChanged("Estado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property FechaIngreso() As Date
            Get
                Return Me.fechaIngresoField
            End Get
            Set
                Me.fechaIngresoField = value
                Me.RaisePropertyChanged("FechaIngreso")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property UsuarioIngreso() As String
            Get
                Return Me.usuarioIngresoField
            End Get
            Set
                Me.usuarioIngresoField = value
                Me.RaisePropertyChanged("UsuarioIngreso")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property FechaActualizacion() As Date
            Get
                Return Me.fechaActualizacionField
            End Get
            Set
                Me.fechaActualizacionField = value
                Me.RaisePropertyChanged("FechaActualizacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=12)>  _
        Public Property UsuarioActualizacion() As String
            Get
                Return Me.usuarioActualizacionField
            End Get
            Set
                Me.usuarioActualizacionField = value
                Me.RaisePropertyChanged("UsuarioActualizacion")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ServiciosGA
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private idServiciosGAField As Integer
        
        Private descripcionServicioField As String
        
        Private estadoField As String
        
        Private fechaIngresoField As Date
        
        Private usuarioIngresoField As String
        
        Private fechaActualizacionField As Date
        
        Private usuarioActualizacionField As String
        
        Private tipoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property idServiciosGA() As Integer
            Get
                Return Me.idServiciosGAField
            End Get
            Set
                Me.idServiciosGAField = value
                Me.RaisePropertyChanged("idServiciosGA")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property DescripcionServicio() As String
            Get
                Return Me.descripcionServicioField
            End Get
            Set
                Me.descripcionServicioField = value
                Me.RaisePropertyChanged("DescripcionServicio")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
                Me.RaisePropertyChanged("Estado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property FechaIngreso() As Date
            Get
                Return Me.fechaIngresoField
            End Get
            Set
                Me.fechaIngresoField = value
                Me.RaisePropertyChanged("FechaIngreso")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property UsuarioIngreso() As String
            Get
                Return Me.usuarioIngresoField
            End Get
            Set
                Me.usuarioIngresoField = value
                Me.RaisePropertyChanged("UsuarioIngreso")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property FechaActualizacion() As Date
            Get
                Return Me.fechaActualizacionField
            End Get
            Set
                Me.fechaActualizacionField = value
                Me.RaisePropertyChanged("FechaActualizacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property UsuarioActualizacion() As String
            Get
                Return Me.usuarioActualizacionField
            End Get
            Set
                Me.usuarioActualizacionField = value
                Me.RaisePropertyChanged("UsuarioActualizacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property Tipo() As String
            Get
                Return Me.tipoField
            End Get
            Set
                Me.tipoField = value
                Me.RaisePropertyChanged("Tipo")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(TipoProcesoAlmacenajeCargaRequest)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(VuelosCanceladosRequest)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ServConsuClienteRequest)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(PeriodicidadRequest)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(PlantillaClienServRequest)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ServiciosGARequest)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ClienteRequest)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GenericRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private ipAddressField As String
        
        Private terminalIdField As String
        
        Private actionKeyField As String
        
        Private interfaceIdField As String
        
        Private requestDateField As Date
        
        Private pcIdField As String
        
        Private userIdField As String
        
        Private myManagementActionField As ManagementActions
        
        Private sessionKeyField As System.Guid
        
        Private idField As System.Guid
        
        Private fechaIniField As Date
        
        Private fechaFinField As Date
        
        Private codigoVueloField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property IpAddress() As String
            Get
                Return Me.ipAddressField
            End Get
            Set
                Me.ipAddressField = value
                Me.RaisePropertyChanged("IpAddress")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property TerminalId() As String
            Get
                Return Me.terminalIdField
            End Get
            Set
                Me.terminalIdField = value
                Me.RaisePropertyChanged("TerminalId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property ActionKey() As String
            Get
                Return Me.actionKeyField
            End Get
            Set
                Me.actionKeyField = value
                Me.RaisePropertyChanged("ActionKey")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property InterfaceId() As String
            Get
                Return Me.interfaceIdField
            End Get
            Set
                Me.interfaceIdField = value
                Me.RaisePropertyChanged("InterfaceId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property RequestDate() As Date
            Get
                Return Me.requestDateField
            End Get
            Set
                Me.requestDateField = value
                Me.RaisePropertyChanged("RequestDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property PcId() As String
            Get
                Return Me.pcIdField
            End Get
            Set
                Me.pcIdField = value
                Me.RaisePropertyChanged("PcId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property UserId() As String
            Get
                Return Me.userIdField
            End Get
            Set
                Me.userIdField = value
                Me.RaisePropertyChanged("UserId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property myManagementAction() As ManagementActions
            Get
                Return Me.myManagementActionField
            End Get
            Set
                Me.myManagementActionField = value
                Me.RaisePropertyChanged("myManagementAction")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property SessionKey() As System.Guid
            Get
                Return Me.sessionKeyField
            End Get
            Set
                Me.sessionKeyField = value
                Me.RaisePropertyChanged("SessionKey")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property id() As System.Guid
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
                Me.RaisePropertyChanged("id")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property fechaIni() As Date
            Get
                Return Me.fechaIniField
            End Get
            Set
                Me.fechaIniField = value
                Me.RaisePropertyChanged("fechaIni")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property fechaFin() As Date
            Get
                Return Me.fechaFinField
            End Get
            Set
                Me.fechaFinField = value
                Me.RaisePropertyChanged("fechaFin")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=12)>  _
        Public Property codigoVuelo() As String
            Get
                Return Me.codigoVueloField
            End Get
            Set
                Me.codigoVueloField = value
                Me.RaisePropertyChanged("codigoVuelo")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum ManagementActions
        
        '''<remarks/>
        [NOTHING]
        
        '''<remarks/>
        INSERT
        
        '''<remarks/>
        UPDATE
        
        '''<remarks/>
        DELETE
        
        '''<remarks/>
        QUERY
        
        '''<remarks/>
        REPLICATED
        
        '''<remarks/>
        REFRESH
        
        '''<remarks/>
        EXPORT
        
        '''<remarks/>
        SEARCH
        
        '''<remarks/>
        PRINT
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class TipoProcesoAlmacenajeCargaRequest
        Inherits GenericRequest
        
        Private tipoProcesoAlmacenajeCargaField As TipoProcesoAlmacenajeCarga
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property TipoProcesoAlmacenajeCarga() As TipoProcesoAlmacenajeCarga
            Get
                Return Me.tipoProcesoAlmacenajeCargaField
            End Get
            Set
                Me.tipoProcesoAlmacenajeCargaField = value
                Me.RaisePropertyChanged("TipoProcesoAlmacenajeCarga")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class VuelosCanceladosRequest
        Inherits GenericRequest
        
        Private vuelosCanceladosField As VuelosCancelados
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property VuelosCancelados() As VuelosCancelados
            Get
                Return Me.vuelosCanceladosField
            End Get
            Set
                Me.vuelosCanceladosField = value
                Me.RaisePropertyChanged("VuelosCancelados")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ServConsuClienteRequest
        Inherits GenericRequest
        
        Private servConsuClienteField As ServConsuCliente
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property ServConsuCliente() As ServConsuCliente
            Get
                Return Me.servConsuClienteField
            End Get
            Set
                Me.servConsuClienteField = value
                Me.RaisePropertyChanged("ServConsuCliente")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class PeriodicidadRequest
        Inherits GenericRequest
        
        Private periodicidadField As Periodicidad
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Periodicidad() As Periodicidad
            Get
                Return Me.periodicidadField
            End Get
            Set
                Me.periodicidadField = value
                Me.RaisePropertyChanged("Periodicidad")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class PlantillaClienServRequest
        Inherits GenericRequest
        
        Private plantillaClienteServicioField As PlantillaClienServ
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property PlantillaClienteServicio() As PlantillaClienServ
            Get
                Return Me.plantillaClienteServicioField
            End Get
            Set
                Me.plantillaClienteServicioField = value
                Me.RaisePropertyChanged("PlantillaClienteServicio")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ServiciosGARequest
        Inherits GenericRequest
        
        Private serviciosGAField As ServiciosGA
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property ServiciosGA() As ServiciosGA
            Get
                Return Me.serviciosGAField
            End Get
            Set
                Me.serviciosGAField = value
                Me.RaisePropertyChanged("ServiciosGA")
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface FacturacionSoapChannel
        Inherits Server.Facturacion.FacturacionSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class FacturacionSoapClient
        Inherits System.ServiceModel.ClientBase(Of Server.Facturacion.FacturacionSoap)
        Implements Server.Facturacion.FacturacionSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function MantClientes(ByVal req As Server.Facturacion.ClienteRequest) As Server.Facturacion.ClienteResponse Implements Server.Facturacion.FacturacionSoap.MantClientes
            Return MyBase.Channel.MantClientes(req)
        End Function
        
        Public Function MantClientesAsync(ByVal req As Server.Facturacion.ClienteRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.ClienteResponse) Implements Server.Facturacion.FacturacionSoap.MantClientesAsync
            Return MyBase.Channel.MantClientesAsync(req)
        End Function
        
        Public Function MantServiciosGA(ByVal req As Server.Facturacion.ServiciosGARequest) As Server.Facturacion.ServiciosGAResponse Implements Server.Facturacion.FacturacionSoap.MantServiciosGA
            Return MyBase.Channel.MantServiciosGA(req)
        End Function
        
        Public Function MantServiciosGAAsync(ByVal req As Server.Facturacion.ServiciosGARequest) As System.Threading.Tasks.Task(Of Server.Facturacion.ServiciosGAResponse) Implements Server.Facturacion.FacturacionSoap.MantServiciosGAAsync
            Return MyBase.Channel.MantServiciosGAAsync(req)
        End Function
        
        Public Function MantPlantiClienteServ(ByVal req As Server.Facturacion.PlantillaClienServRequest) As Server.Facturacion.PlantillaClienServResponse Implements Server.Facturacion.FacturacionSoap.MantPlantiClienteServ
            Return MyBase.Channel.MantPlantiClienteServ(req)
        End Function
        
        Public Function MantPlantiClienteServAsync(ByVal req As Server.Facturacion.PlantillaClienServRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.PlantillaClienServResponse) Implements Server.Facturacion.FacturacionSoap.MantPlantiClienteServAsync
            Return MyBase.Channel.MantPlantiClienteServAsync(req)
        End Function
        
        Public Function MantPeriodicidad(ByVal req As Server.Facturacion.PeriodicidadRequest) As Server.Facturacion.PeriodicidadResponse Implements Server.Facturacion.FacturacionSoap.MantPeriodicidad
            Return MyBase.Channel.MantPeriodicidad(req)
        End Function
        
        Public Function MantPeriodicidadAsync(ByVal req As Server.Facturacion.PeriodicidadRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.PeriodicidadResponse) Implements Server.Facturacion.FacturacionSoap.MantPeriodicidadAsync
            Return MyBase.Channel.MantPeriodicidadAsync(req)
        End Function
        
        Public Function MantServConsuCliente(ByVal req As Server.Facturacion.ServConsuClienteRequest) As Server.Facturacion.ServConsuClienteResponse Implements Server.Facturacion.FacturacionSoap.MantServConsuCliente
            Return MyBase.Channel.MantServConsuCliente(req)
        End Function
        
        Public Function MantServConsuClienteAsync(ByVal req As Server.Facturacion.ServConsuClienteRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.ServConsuClienteResponse) Implements Server.Facturacion.FacturacionSoap.MantServConsuClienteAsync
            Return MyBase.Channel.MantServConsuClienteAsync(req)
        End Function
        
        Public Function MantVuelosCancelados(ByVal req As Server.Facturacion.VuelosCanceladosRequest) As Server.Facturacion.VuelosCanceladosResponse Implements Server.Facturacion.FacturacionSoap.MantVuelosCancelados
            Return MyBase.Channel.MantVuelosCancelados(req)
        End Function
        
        Public Function MantVuelosCanceladosAsync(ByVal req As Server.Facturacion.VuelosCanceladosRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.VuelosCanceladosResponse) Implements Server.Facturacion.FacturacionSoap.MantVuelosCanceladosAsync
            Return MyBase.Channel.MantVuelosCanceladosAsync(req)
        End Function
        
        Public Function GetClientes(ByVal req As Server.Facturacion.ClienteRequest) As Server.Facturacion.ClienteResponse Implements Server.Facturacion.FacturacionSoap.GetClientes
            Return MyBase.Channel.GetClientes(req)
        End Function
        
        Public Function GetClientesAsync(ByVal req As Server.Facturacion.ClienteRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.ClienteResponse) Implements Server.Facturacion.FacturacionSoap.GetClientesAsync
            Return MyBase.Channel.GetClientesAsync(req)
        End Function
        
        Public Function GetServiciosGA(ByVal req As Server.Facturacion.ServiciosGARequest) As Server.Facturacion.ServiciosGAResponse Implements Server.Facturacion.FacturacionSoap.GetServiciosGA
            Return MyBase.Channel.GetServiciosGA(req)
        End Function
        
        Public Function GetServiciosGAAsync(ByVal req As Server.Facturacion.ServiciosGARequest) As System.Threading.Tasks.Task(Of Server.Facturacion.ServiciosGAResponse) Implements Server.Facturacion.FacturacionSoap.GetServiciosGAAsync
            Return MyBase.Channel.GetServiciosGAAsync(req)
        End Function
        
        Public Function GetPeriodicidad(ByVal req As Server.Facturacion.PeriodicidadRequest) As Server.Facturacion.PeriodicidadResponse Implements Server.Facturacion.FacturacionSoap.GetPeriodicidad
            Return MyBase.Channel.GetPeriodicidad(req)
        End Function
        
        Public Function GetPeriodicidadAsync(ByVal req As Server.Facturacion.PeriodicidadRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.PeriodicidadResponse) Implements Server.Facturacion.FacturacionSoap.GetPeriodicidadAsync
            Return MyBase.Channel.GetPeriodicidadAsync(req)
        End Function
        
        Public Function GetPlantiClienteServ(ByVal req As Server.Facturacion.PlantillaClienServRequest) As Server.Facturacion.PlantillaClienServResponse Implements Server.Facturacion.FacturacionSoap.GetPlantiClienteServ
            Return MyBase.Channel.GetPlantiClienteServ(req)
        End Function
        
        Public Function GetPlantiClienteServAsync(ByVal req As Server.Facturacion.PlantillaClienServRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.PlantillaClienServResponse) Implements Server.Facturacion.FacturacionSoap.GetPlantiClienteServAsync
            Return MyBase.Channel.GetPlantiClienteServAsync(req)
        End Function
        
        Public Function GetTipoProceAlmacenaCarga(ByVal req As Server.Facturacion.TipoProcesoAlmacenajeCargaRequest) As Server.Facturacion.TipoProcesoAlmacenajeCargaResponse Implements Server.Facturacion.FacturacionSoap.GetTipoProceAlmacenaCarga
            Return MyBase.Channel.GetTipoProceAlmacenaCarga(req)
        End Function
        
        Public Function GetTipoProceAlmacenaCargaAsync(ByVal req As Server.Facturacion.TipoProcesoAlmacenajeCargaRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.TipoProcesoAlmacenajeCargaResponse) Implements Server.Facturacion.FacturacionSoap.GetTipoProceAlmacenaCargaAsync
            Return MyBase.Channel.GetTipoProceAlmacenaCargaAsync(req)
        End Function
        
        Public Function PreFactObtenerPesoVolumenVuelo(ByVal req As Server.Facturacion.PlantillaClienServRequest) As Server.Facturacion.PlantillaClienServResponse Implements Server.Facturacion.FacturacionSoap.PreFactObtenerPesoVolumenVuelo
            Return MyBase.Channel.PreFactObtenerPesoVolumenVuelo(req)
        End Function
        
        Public Function PreFactObtenerPesoVolumenVueloAsync(ByVal req As Server.Facturacion.PlantillaClienServRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.PlantillaClienServResponse) Implements Server.Facturacion.FacturacionSoap.PreFactObtenerPesoVolumenVueloAsync
            Return MyBase.Channel.PreFactObtenerPesoVolumenVueloAsync(req)
        End Function
        
        Public Function PreFactObtenerCantVuelosAgencia(ByVal req As Server.Facturacion.PlantillaClienServRequest) As Server.Facturacion.PlantillaClienServResponse Implements Server.Facturacion.FacturacionSoap.PreFactObtenerCantVuelosAgencia
            Return MyBase.Channel.PreFactObtenerCantVuelosAgencia(req)
        End Function
        
        Public Function PreFactObtenerCantVuelosAgenciaAsync(ByVal req As Server.Facturacion.PlantillaClienServRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.PlantillaClienServResponse) Implements Server.Facturacion.FacturacionSoap.PreFactObtenerCantVuelosAgenciaAsync
            Return MyBase.Channel.PreFactObtenerCantVuelosAgenciaAsync(req)
        End Function
        
        Public Function PreFactObtenerPesoVolumenGuia(ByVal req As Server.Facturacion.PlantillaClienServRequest) As Server.Facturacion.PlantillaClienServResponse Implements Server.Facturacion.FacturacionSoap.PreFactObtenerPesoVolumenGuia
            Return MyBase.Channel.PreFactObtenerPesoVolumenGuia(req)
        End Function
        
        Public Function PreFactObtenerPesoVolumenGuiaAsync(ByVal req As Server.Facturacion.PlantillaClienServRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.PlantillaClienServResponse) Implements Server.Facturacion.FacturacionSoap.PreFactObtenerPesoVolumenGuiaAsync
            Return MyBase.Channel.PreFactObtenerPesoVolumenGuiaAsync(req)
        End Function
        
        Public Function PreFactObtenerTiempoAlmaceContainer(ByVal req As Server.Facturacion.PlantillaClienServRequest) As Server.Facturacion.PlantillaClienServResponse Implements Server.Facturacion.FacturacionSoap.PreFactObtenerTiempoAlmaceContainer
            Return MyBase.Channel.PreFactObtenerTiempoAlmaceContainer(req)
        End Function
        
        Public Function PreFactObtenerTiempoAlmaceContainerAsync(ByVal req As Server.Facturacion.PlantillaClienServRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.PlantillaClienServResponse) Implements Server.Facturacion.FacturacionSoap.PreFactObtenerTiempoAlmaceContainerAsync
            Return MyBase.Channel.PreFactObtenerTiempoAlmaceContainerAsync(req)
        End Function
        
        Public Function GetSerConsuCliente(ByVal req As Server.Facturacion.ServConsuClienteRequest) As Server.Facturacion.ServConsuClienteResponse Implements Server.Facturacion.FacturacionSoap.GetSerConsuCliente
            Return MyBase.Channel.GetSerConsuCliente(req)
        End Function
        
        Public Function GetSerConsuClienteAsync(ByVal req As Server.Facturacion.ServConsuClienteRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.ServConsuClienteResponse) Implements Server.Facturacion.FacturacionSoap.GetSerConsuClienteAsync
            Return MyBase.Channel.GetSerConsuClienteAsync(req)
        End Function
        
        Public Function GetVuelosCancelados(ByVal req As Server.Facturacion.VuelosCanceladosRequest) As Server.Facturacion.VuelosCanceladosResponse Implements Server.Facturacion.FacturacionSoap.GetVuelosCancelados
            Return MyBase.Channel.GetVuelosCancelados(req)
        End Function
        
        Public Function GetVuelosCanceladosAsync(ByVal req As Server.Facturacion.VuelosCanceladosRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.VuelosCanceladosResponse) Implements Server.Facturacion.FacturacionSoap.GetVuelosCanceladosAsync
            Return MyBase.Channel.GetVuelosCanceladosAsync(req)
        End Function
        
        Public Function GetVuelosGuias(ByVal req As Server.Facturacion.VuelosCanceladosRequest) As Server.Facturacion.VuelosCanceladosResponse Implements Server.Facturacion.FacturacionSoap.GetVuelosGuias
            Return MyBase.Channel.GetVuelosGuias(req)
        End Function
        
        Public Function GetVuelosGuiasAsync(ByVal req As Server.Facturacion.VuelosCanceladosRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.VuelosCanceladosResponse) Implements Server.Facturacion.FacturacionSoap.GetVuelosGuiasAsync
            Return MyBase.Channel.GetVuelosGuiasAsync(req)
        End Function
        
        Public Function PreFactObtenerServConsuCliente(ByVal req As Server.Facturacion.ServConsuClienteRequest) As Server.Facturacion.ServConsuClienteResponse Implements Server.Facturacion.FacturacionSoap.PreFactObtenerServConsuCliente
            Return MyBase.Channel.PreFactObtenerServConsuCliente(req)
        End Function
        
        Public Function PreFactObtenerServConsuClienteAsync(ByVal req As Server.Facturacion.ServConsuClienteRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.ServConsuClienteResponse) Implements Server.Facturacion.FacturacionSoap.PreFactObtenerServConsuClienteAsync
            Return MyBase.Channel.PreFactObtenerServConsuClienteAsync(req)
        End Function
        
        Public Function PreFactObtenerPesoVolumenPorBriefGuia(ByVal req As Server.Facturacion.ServConsuClienteRequest) As Server.Facturacion.ServConsuClienteResponse Implements Server.Facturacion.FacturacionSoap.PreFactObtenerPesoVolumenPorBriefGuia
            Return MyBase.Channel.PreFactObtenerPesoVolumenPorBriefGuia(req)
        End Function
        
        Public Function PreFactObtenerPesoVolumenPorBriefGuiaAsync(ByVal req As Server.Facturacion.ServConsuClienteRequest) As System.Threading.Tasks.Task(Of Server.Facturacion.ServConsuClienteResponse) Implements Server.Facturacion.FacturacionSoap.PreFactObtenerPesoVolumenPorBriefGuiaAsync
            Return MyBase.Channel.PreFactObtenerPesoVolumenPorBriefGuiaAsync(req)
        End Function
    End Class
End Namespace
