'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://espc.org/", ConfigurationName:="ServiceReference1.ControlTempSoap")>  _
    Public Interface ControlTempSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://espc.org/ObtenerCuartosFrios", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function ObtenerCuartosFrios(ByVal req As ServiceReference1.TempRequest) As ServiceReference1.TempResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://espc.org/ObtenerCuartosFrios", ReplyAction:="*")>  _
        Function ObtenerCuartosFriosAsync(ByVal req As ServiceReference1.TempRequest) As System.Threading.Tasks.Task(Of ServiceReference1.TempResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://espc.org/ObtenerConfTemp", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function ObtenerConfTemp(ByVal req As ServiceReference1.TempRequest) As ServiceReference1.TempResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://espc.org/ObtenerConfTemp", ReplyAction:="*")>  _
        Function ObtenerConfTempAsync(ByVal req As ServiceReference1.TempRequest) As System.Threading.Tasks.Task(Of ServiceReference1.TempResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://espc.org/ObtenerTempAct", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function ObtenerTempAct(ByVal req As ServiceReference1.TempRequest) As ServiceReference1.TempResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://espc.org/ObtenerTempAct", ReplyAction:="*")>  _
        Function ObtenerTempActAsync(ByVal req As ServiceReference1.TempRequest) As System.Threading.Tasks.Task(Of ServiceReference1.TempResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://espc.org/RegConfTemp", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function RegConfTemp(ByVal req As ServiceReference1.TempRequest) As ServiceReference1.TempResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://espc.org/RegConfTemp", ReplyAction:="*")>  _
        Function RegConfTempAsync(ByVal req As ServiceReference1.TempRequest) As System.Threading.Tasks.Task(Of ServiceReference1.TempResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://espc.org/RegCuartoFrio", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function RegCuartoFrio(ByVal req As ServiceReference1.TempRequest) As ServiceReference1.TempResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://espc.org/RegCuartoFrio", ReplyAction:="*")>  _
        Function RegCuartoFrioAsync(ByVal req As ServiceReference1.TempRequest) As System.Threading.Tasks.Task(Of ServiceReference1.TempResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://espc.org/RegTemperatura", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function RegTemperatura(ByVal req As ServiceReference1.TempRequest) As ServiceReference1.TempResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://espc.org/RegTemperatura", ReplyAction:="*")>  _
        Function RegTemperaturaAsync(ByVal req As ServiceReference1.TempRequest) As System.Threading.Tasks.Task(Of ServiceReference1.TempResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://espc.org/RegTemperaturaHist", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function RegTemperaturaHist(ByVal req As ServiceReference1.TempRequest) As ServiceReference1.TempResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://espc.org/RegTemperaturaHist", ReplyAction:="*")>  _
        Function RegTemperaturaHistAsync(ByVal req As ServiceReference1.TempRequest) As System.Threading.Tasks.Task(Of ServiceReference1.TempResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://espc.org/ActualizaVersion", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function ActualizaVersion(ByVal req As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://espc.org/ActualizaVersion", ReplyAction:="*")>  _
        Function ActualizaVersionAsync(ByVal req As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://espc.org/ObtenerReportTemp", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function ObtenerReportTemp(ByVal req As ServiceReference1.TempRequest) As ServiceReference1.TempResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://espc.org/ObtenerReportTemp", ReplyAction:="*")>  _
        Function ObtenerReportTempAsync(ByVal req As ServiceReference1.TempRequest) As System.Threading.Tasks.Task(Of ServiceReference1.TempResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://espc.org/ObtenerCuartoFrioIdProIdGui", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function ObtenerCuartoFrioIdProIdGui(ByVal req As ServiceReference1.TempBitacoraCuartoRequest) As ServiceReference1.TempBitacoraCuartoResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://espc.org/ObtenerCuartoFrioIdProIdGui", ReplyAction:="*")>  _
        Function ObtenerCuartoFrioIdProIdGuiAsync(ByVal req As ServiceReference1.TempBitacoraCuartoRequest) As System.Threading.Tasks.Task(Of ServiceReference1.TempBitacoraCuartoResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://espc.org/AgregaBitacoraCargaCuarto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function AgregaBitacoraCargaCuarto(ByVal req As ServiceReference1.TempBitacoraCuartoRequest) As ServiceReference1.TempBitacoraCuartoResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://espc.org/AgregaBitacoraCargaCuarto", ReplyAction:="*")>  _
        Function AgregaBitacoraCargaCuartoAsync(ByVal req As ServiceReference1.TempBitacoraCuartoRequest) As System.Threading.Tasks.Task(Of ServiceReference1.TempBitacoraCuartoResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://espc.org/ObtenerVuelosElemen", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function ObtenerVuelosElemen(ByVal req As ServiceReference1.TempBitacoraCuartoRequest) As ServiceReference1.TempBitacoraCuartoResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://espc.org/ObtenerVuelosElemen", ReplyAction:="*")>  _
        Function ObtenerVuelosElemenAsync(ByVal req As ServiceReference1.TempBitacoraCuartoRequest) As System.Threading.Tasks.Task(Of ServiceReference1.TempBitacoraCuartoResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://espc.org/ObtenerParametrosNoti", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function ObtenerParametrosNoti(ByVal req As ServiceReference1.NotificacionTempRequest) As ServiceReference1.NotificacionTempResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://espc.org/ObtenerParametrosNoti", ReplyAction:="*")>  _
        Function ObtenerParametrosNotiAsync(ByVal req As ServiceReference1.NotificacionTempRequest) As System.Threading.Tasks.Task(Of ServiceReference1.NotificacionTempResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://espc.org/MantNotificacionTemp", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function MantNotificacionTemp(ByVal req As ServiceReference1.NotificacionTempRequest) As ServiceReference1.NotificacionTempResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://espc.org/MantNotificacionTemp", ReplyAction:="*")>  _
        Function MantNotificacionTempAsync(ByVal req As ServiceReference1.NotificacionTempRequest) As System.Threading.Tasks.Task(Of ServiceReference1.NotificacionTempResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://espc.org/ObtenerRegCuartProduc", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericResponse)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(GenericRequest))>  _
        Function ObtenerRegCuartProduc() As ServiceReference1.NotificacionTempResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://espc.org/ObtenerRegCuartProduc", ReplyAction:="*")>  _
        Function ObtenerRegCuartProducAsync() As System.Threading.Tasks.Task(Of ServiceReference1.NotificacionTempResponse)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://espc.org/")>  _
    Partial Public Class TempRequest
        Inherits GenericRequest
        
        Private nombreCuartoFrioField As String
        
        Private puertoField As String
        
        Private estadoField As String
        
        Private humedadField As Double
        
        Private centigradoField As Double
        
        Private fahrenheitField As Double
        
        Private descripcionField As String
        
        Private fechaInicioField As Date
        
        Private fechaFinalField As Date
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property NombreCuartoFrio() As String
            Get
                Return Me.nombreCuartoFrioField
            End Get
            Set
                Me.nombreCuartoFrioField = value
                Me.RaisePropertyChanged("NombreCuartoFrio")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Puerto() As String
            Get
                Return Me.puertoField
            End Get
            Set
                Me.puertoField = value
                Me.RaisePropertyChanged("Puerto")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
                Me.RaisePropertyChanged("Estado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property Humedad() As Double
            Get
                Return Me.humedadField
            End Get
            Set
                Me.humedadField = value
                Me.RaisePropertyChanged("Humedad")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property Centigrado() As Double
            Get
                Return Me.centigradoField
            End Get
            Set
                Me.centigradoField = value
                Me.RaisePropertyChanged("Centigrado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property fahrenheit() As Double
            Get
                Return Me.fahrenheitField
            End Get
            Set
                Me.fahrenheitField = value
                Me.RaisePropertyChanged("fahrenheit")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property Descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
                Me.RaisePropertyChanged("Descripcion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property FechaInicio() As Date
            Get
                Return Me.fechaInicioField
            End Get
            Set
                Me.fechaInicioField = value
                Me.RaisePropertyChanged("FechaInicio")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property FechaFinal() As Date
            Get
                Return Me.fechaFinalField
            End Get
            Set
                Me.fechaFinalField = value
                Me.RaisePropertyChanged("FechaFinal")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(NotificacionTempRequest)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(TempBitacoraCuartoRequest)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(TempRequest)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://espc.org/")>  _
    Partial Public Class GenericRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private ipAddressField As String
        
        Private terminalIdField As String
        
        Private actionKeyField As String
        
        Private interfaceIdField As String
        
        Private requestDateField As Date
        
        Private pcIdField As String
        
        Private userIdField As String
        
        Private myManagementActionField As ManagementActions
        
        Private sessionKeyField As System.Guid
        
        Private idField As System.Guid
        
        Private fechaIniField As Date
        
        Private fechaFinField As Date
        
        Private codigoVueloField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property IpAddress() As String
            Get
                Return Me.ipAddressField
            End Get
            Set
                Me.ipAddressField = value
                Me.RaisePropertyChanged("IpAddress")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property TerminalId() As String
            Get
                Return Me.terminalIdField
            End Get
            Set
                Me.terminalIdField = value
                Me.RaisePropertyChanged("TerminalId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property ActionKey() As String
            Get
                Return Me.actionKeyField
            End Get
            Set
                Me.actionKeyField = value
                Me.RaisePropertyChanged("ActionKey")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property InterfaceId() As String
            Get
                Return Me.interfaceIdField
            End Get
            Set
                Me.interfaceIdField = value
                Me.RaisePropertyChanged("InterfaceId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property RequestDate() As Date
            Get
                Return Me.requestDateField
            End Get
            Set
                Me.requestDateField = value
                Me.RaisePropertyChanged("RequestDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property PcId() As String
            Get
                Return Me.pcIdField
            End Get
            Set
                Me.pcIdField = value
                Me.RaisePropertyChanged("PcId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property UserId() As String
            Get
                Return Me.userIdField
            End Get
            Set
                Me.userIdField = value
                Me.RaisePropertyChanged("UserId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property myManagementAction() As ManagementActions
            Get
                Return Me.myManagementActionField
            End Get
            Set
                Me.myManagementActionField = value
                Me.RaisePropertyChanged("myManagementAction")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property SessionKey() As System.Guid
            Get
                Return Me.sessionKeyField
            End Get
            Set
                Me.sessionKeyField = value
                Me.RaisePropertyChanged("SessionKey")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property id() As System.Guid
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
                Me.RaisePropertyChanged("id")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property fechaIni() As Date
            Get
                Return Me.fechaIniField
            End Get
            Set
                Me.fechaIniField = value
                Me.RaisePropertyChanged("fechaIni")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property fechaFin() As Date
            Get
                Return Me.fechaFinField
            End Get
            Set
                Me.fechaFinField = value
                Me.RaisePropertyChanged("fechaFin")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=12)>  _
        Public Property codigoVuelo() As String
            Get
                Return Me.codigoVueloField
            End Get
            Set
                Me.codigoVueloField = value
                Me.RaisePropertyChanged("codigoVuelo")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://espc.org/")>  _
    Public Enum ManagementActions
        
        '''<remarks/>
        [NOTHING]
        
        '''<remarks/>
        INSERT
        
        '''<remarks/>
        UPDATE
        
        '''<remarks/>
        DELETE
        
        '''<remarks/>
        QUERY
        
        '''<remarks/>
        REPLICATED
        
        '''<remarks/>
        REFRESH
        
        '''<remarks/>
        EXPORT
        
        '''<remarks/>
        SEARCH
        
        '''<remarks/>
        PRINT
    End Enum
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(NotificacionTempResponse)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(TempBitacoraCuartoResponse)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(TempResponse)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://espc.org/")>  _
    Partial Public Class GenericResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private errorCodeField As Integer
        
        Private errorMessageField As String
        
        Private actionResultField As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property ErrorCode() As Integer
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
                Me.RaisePropertyChanged("ErrorCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property ErrorMessage() As String
            Get
                Return Me.errorMessageField
            End Get
            Set
                Me.errorMessageField = value
                Me.RaisePropertyChanged("ErrorMessage")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property ActionResult() As Boolean
            Get
                Return Me.actionResultField
            End Get
            Set
                Me.actionResultField = value
                Me.RaisePropertyChanged("ActionResult")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://espc.org/")>  _
    Partial Public Class NotificacionTempResponse
        Inherits GenericResponse
        
        Private dsResultField As System.Data.DataSet
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property dsResult() As System.Data.DataSet
            Get
                Return Me.dsResultField
            End Get
            Set
                Me.dsResultField = value
                Me.RaisePropertyChanged("dsResult")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://espc.org/")>  _
    Partial Public Class TempBitacoraCuartoResponse
        Inherits GenericResponse
        
        Private dsResultField As System.Data.DataSet
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property dsResult() As System.Data.DataSet
            Get
                Return Me.dsResultField
            End Get
            Set
                Me.dsResultField = value
                Me.RaisePropertyChanged("dsResult")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://espc.org/")>  _
    Partial Public Class TempResponse
        Inherits GenericResponse
        
        Private dsResultField As System.Data.DataSet
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property DsResult() As System.Data.DataSet
            Get
                Return Me.dsResultField
            End Get
            Set
                Me.dsResultField = value
                Me.RaisePropertyChanged("DsResult")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://espc.org/")>  _
    Partial Public Class NotificacionTemp
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private id_notificacion_tempField As Integer
        
        Private idProductoField As System.Guid
        
        Private temp_minField As Double
        
        Private temp_maxField As Double
        
        Private estadoField As String
        
        Private usuarioIngresoField As String
        
        Private fechaIngresoField As Date
        
        Private usuarioActualizacionField As String
        
        Private fechaActualizacionField As Date
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property id_notificacion_temp() As Integer
            Get
                Return Me.id_notificacion_tempField
            End Get
            Set
                Me.id_notificacion_tempField = value
                Me.RaisePropertyChanged("id_notificacion_temp")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property idProducto() As System.Guid
            Get
                Return Me.idProductoField
            End Get
            Set
                Me.idProductoField = value
                Me.RaisePropertyChanged("idProducto")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property temp_min() As Double
            Get
                Return Me.temp_minField
            End Get
            Set
                Me.temp_minField = value
                Me.RaisePropertyChanged("temp_min")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property temp_max() As Double
            Get
                Return Me.temp_maxField
            End Get
            Set
                Me.temp_maxField = value
                Me.RaisePropertyChanged("temp_max")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property Estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
                Me.RaisePropertyChanged("Estado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property UsuarioIngreso() As String
            Get
                Return Me.usuarioIngresoField
            End Get
            Set
                Me.usuarioIngresoField = value
                Me.RaisePropertyChanged("UsuarioIngreso")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property FechaIngreso() As Date
            Get
                Return Me.fechaIngresoField
            End Get
            Set
                Me.fechaIngresoField = value
                Me.RaisePropertyChanged("FechaIngreso")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property UsuarioActualizacion() As String
            Get
                Return Me.usuarioActualizacionField
            End Get
            Set
                Me.usuarioActualizacionField = value
                Me.RaisePropertyChanged("UsuarioActualizacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property FechaActualizacion() As Date
            Get
                Return Me.fechaActualizacionField
            End Get
            Set
                Me.fechaActualizacionField = value
                Me.RaisePropertyChanged("FechaActualizacion")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://espc.org/")>  _
    Partial Public Class TempBitacoraCuarto
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private idProcesoField As System.Guid
        
        Private idGuiaField As System.Guid
        
        Private idElementoField As String
        
        Private cuartoAnterirorField As String
        
        Private cuartoActualField As String
        
        Private usuarioIngresoField As String
        
        Private regCargaCuartoFrioField As String
        
        Private totalField As Integer
        
        Private tipoConsultaField As Integer
        
        Private idAgenciaField As System.Guid
        
        Private fechaInicioField As Date
        
        Private fechaFinField As Date
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property idProceso() As System.Guid
            Get
                Return Me.idProcesoField
            End Get
            Set
                Me.idProcesoField = value
                Me.RaisePropertyChanged("idProceso")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property idGuia() As System.Guid
            Get
                Return Me.idGuiaField
            End Get
            Set
                Me.idGuiaField = value
                Me.RaisePropertyChanged("idGuia")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property idElemento() As String
            Get
                Return Me.idElementoField
            End Get
            Set
                Me.idElementoField = value
                Me.RaisePropertyChanged("idElemento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property CuartoAnteriror() As String
            Get
                Return Me.cuartoAnterirorField
            End Get
            Set
                Me.cuartoAnterirorField = value
                Me.RaisePropertyChanged("CuartoAnteriror")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property CuartoActual() As String
            Get
                Return Me.cuartoActualField
            End Get
            Set
                Me.cuartoActualField = value
                Me.RaisePropertyChanged("CuartoActual")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property UsuarioIngreso() As String
            Get
                Return Me.usuarioIngresoField
            End Get
            Set
                Me.usuarioIngresoField = value
                Me.RaisePropertyChanged("UsuarioIngreso")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property RegCargaCuartoFrio() As String
            Get
                Return Me.regCargaCuartoFrioField
            End Get
            Set
                Me.regCargaCuartoFrioField = value
                Me.RaisePropertyChanged("RegCargaCuartoFrio")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property total() As Integer
            Get
                Return Me.totalField
            End Get
            Set
                Me.totalField = value
                Me.RaisePropertyChanged("total")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property TipoConsulta() As Integer
            Get
                Return Me.tipoConsultaField
            End Get
            Set
                Me.tipoConsultaField = value
                Me.RaisePropertyChanged("TipoConsulta")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property idAgencia() As System.Guid
            Get
                Return Me.idAgenciaField
            End Get
            Set
                Me.idAgenciaField = value
                Me.RaisePropertyChanged("idAgencia")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property fechaInicio() As Date
            Get
                Return Me.fechaInicioField
            End Get
            Set
                Me.fechaInicioField = value
                Me.RaisePropertyChanged("fechaInicio")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property fechaFin() As Date
            Get
                Return Me.fechaFinField
            End Get
            Set
                Me.fechaFinField = value
                Me.RaisePropertyChanged("fechaFin")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://espc.org/")>  _
    Partial Public Class NotificacionTempRequest
        Inherits GenericRequest
        
        Private notificacionTempField As NotificacionTemp
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property NotificacionTemp() As NotificacionTemp
            Get
                Return Me.notificacionTempField
            End Get
            Set
                Me.notificacionTempField = value
                Me.RaisePropertyChanged("NotificacionTemp")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://espc.org/")>  _
    Partial Public Class TempBitacoraCuartoRequest
        Inherits GenericRequest
        
        Private tempBitacoraCuartoField As TempBitacoraCuarto
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property TempBitacoraCuarto() As TempBitacoraCuarto
            Get
                Return Me.tempBitacoraCuartoField
            End Get
            Set
                Me.tempBitacoraCuartoField = value
                Me.RaisePropertyChanged("TempBitacoraCuarto")
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ControlTempSoapChannel
        Inherits ServiceReference1.ControlTempSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ControlTempSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.ControlTempSoap)
        Implements ServiceReference1.ControlTempSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ObtenerCuartosFrios(ByVal req As ServiceReference1.TempRequest) As ServiceReference1.TempResponse Implements ServiceReference1.ControlTempSoap.ObtenerCuartosFrios
            Return MyBase.Channel.ObtenerCuartosFrios(req)
        End Function
        
        Public Function ObtenerCuartosFriosAsync(ByVal req As ServiceReference1.TempRequest) As System.Threading.Tasks.Task(Of ServiceReference1.TempResponse) Implements ServiceReference1.ControlTempSoap.ObtenerCuartosFriosAsync
            Return MyBase.Channel.ObtenerCuartosFriosAsync(req)
        End Function
        
        Public Function ObtenerConfTemp(ByVal req As ServiceReference1.TempRequest) As ServiceReference1.TempResponse Implements ServiceReference1.ControlTempSoap.ObtenerConfTemp
            Return MyBase.Channel.ObtenerConfTemp(req)
        End Function
        
        Public Function ObtenerConfTempAsync(ByVal req As ServiceReference1.TempRequest) As System.Threading.Tasks.Task(Of ServiceReference1.TempResponse) Implements ServiceReference1.ControlTempSoap.ObtenerConfTempAsync
            Return MyBase.Channel.ObtenerConfTempAsync(req)
        End Function
        
        Public Function ObtenerTempAct(ByVal req As ServiceReference1.TempRequest) As ServiceReference1.TempResponse Implements ServiceReference1.ControlTempSoap.ObtenerTempAct
            Return MyBase.Channel.ObtenerTempAct(req)
        End Function
        
        Public Function ObtenerTempActAsync(ByVal req As ServiceReference1.TempRequest) As System.Threading.Tasks.Task(Of ServiceReference1.TempResponse) Implements ServiceReference1.ControlTempSoap.ObtenerTempActAsync
            Return MyBase.Channel.ObtenerTempActAsync(req)
        End Function
        
        Public Function RegConfTemp(ByVal req As ServiceReference1.TempRequest) As ServiceReference1.TempResponse Implements ServiceReference1.ControlTempSoap.RegConfTemp
            Return MyBase.Channel.RegConfTemp(req)
        End Function
        
        Public Function RegConfTempAsync(ByVal req As ServiceReference1.TempRequest) As System.Threading.Tasks.Task(Of ServiceReference1.TempResponse) Implements ServiceReference1.ControlTempSoap.RegConfTempAsync
            Return MyBase.Channel.RegConfTempAsync(req)
        End Function
        
        Public Function RegCuartoFrio(ByVal req As ServiceReference1.TempRequest) As ServiceReference1.TempResponse Implements ServiceReference1.ControlTempSoap.RegCuartoFrio
            Return MyBase.Channel.RegCuartoFrio(req)
        End Function
        
        Public Function RegCuartoFrioAsync(ByVal req As ServiceReference1.TempRequest) As System.Threading.Tasks.Task(Of ServiceReference1.TempResponse) Implements ServiceReference1.ControlTempSoap.RegCuartoFrioAsync
            Return MyBase.Channel.RegCuartoFrioAsync(req)
        End Function
        
        Public Function RegTemperatura(ByVal req As ServiceReference1.TempRequest) As ServiceReference1.TempResponse Implements ServiceReference1.ControlTempSoap.RegTemperatura
            Return MyBase.Channel.RegTemperatura(req)
        End Function
        
        Public Function RegTemperaturaAsync(ByVal req As ServiceReference1.TempRequest) As System.Threading.Tasks.Task(Of ServiceReference1.TempResponse) Implements ServiceReference1.ControlTempSoap.RegTemperaturaAsync
            Return MyBase.Channel.RegTemperaturaAsync(req)
        End Function
        
        Public Function RegTemperaturaHist(ByVal req As ServiceReference1.TempRequest) As ServiceReference1.TempResponse Implements ServiceReference1.ControlTempSoap.RegTemperaturaHist
            Return MyBase.Channel.RegTemperaturaHist(req)
        End Function
        
        Public Function RegTemperaturaHistAsync(ByVal req As ServiceReference1.TempRequest) As System.Threading.Tasks.Task(Of ServiceReference1.TempResponse) Implements ServiceReference1.ControlTempSoap.RegTemperaturaHistAsync
            Return MyBase.Channel.RegTemperaturaHistAsync(req)
        End Function
        
        Public Function ActualizaVersion(ByVal req As String) As Boolean Implements ServiceReference1.ControlTempSoap.ActualizaVersion
            Return MyBase.Channel.ActualizaVersion(req)
        End Function
        
        Public Function ActualizaVersionAsync(ByVal req As String) As System.Threading.Tasks.Task(Of Boolean) Implements ServiceReference1.ControlTempSoap.ActualizaVersionAsync
            Return MyBase.Channel.ActualizaVersionAsync(req)
        End Function
        
        Public Function ObtenerReportTemp(ByVal req As ServiceReference1.TempRequest) As ServiceReference1.TempResponse Implements ServiceReference1.ControlTempSoap.ObtenerReportTemp
            Return MyBase.Channel.ObtenerReportTemp(req)
        End Function
        
        Public Function ObtenerReportTempAsync(ByVal req As ServiceReference1.TempRequest) As System.Threading.Tasks.Task(Of ServiceReference1.TempResponse) Implements ServiceReference1.ControlTempSoap.ObtenerReportTempAsync
            Return MyBase.Channel.ObtenerReportTempAsync(req)
        End Function
        
        Public Function ObtenerCuartoFrioIdProIdGui(ByVal req As ServiceReference1.TempBitacoraCuartoRequest) As ServiceReference1.TempBitacoraCuartoResponse Implements ServiceReference1.ControlTempSoap.ObtenerCuartoFrioIdProIdGui
            Return MyBase.Channel.ObtenerCuartoFrioIdProIdGui(req)
        End Function
        
        Public Function ObtenerCuartoFrioIdProIdGuiAsync(ByVal req As ServiceReference1.TempBitacoraCuartoRequest) As System.Threading.Tasks.Task(Of ServiceReference1.TempBitacoraCuartoResponse) Implements ServiceReference1.ControlTempSoap.ObtenerCuartoFrioIdProIdGuiAsync
            Return MyBase.Channel.ObtenerCuartoFrioIdProIdGuiAsync(req)
        End Function
        
        Public Function AgregaBitacoraCargaCuarto(ByVal req As ServiceReference1.TempBitacoraCuartoRequest) As ServiceReference1.TempBitacoraCuartoResponse Implements ServiceReference1.ControlTempSoap.AgregaBitacoraCargaCuarto
            Return MyBase.Channel.AgregaBitacoraCargaCuarto(req)
        End Function
        
        Public Function AgregaBitacoraCargaCuartoAsync(ByVal req As ServiceReference1.TempBitacoraCuartoRequest) As System.Threading.Tasks.Task(Of ServiceReference1.TempBitacoraCuartoResponse) Implements ServiceReference1.ControlTempSoap.AgregaBitacoraCargaCuartoAsync
            Return MyBase.Channel.AgregaBitacoraCargaCuartoAsync(req)
        End Function
        
        Public Function ObtenerVuelosElemen(ByVal req As ServiceReference1.TempBitacoraCuartoRequest) As ServiceReference1.TempBitacoraCuartoResponse Implements ServiceReference1.ControlTempSoap.ObtenerVuelosElemen
            Return MyBase.Channel.ObtenerVuelosElemen(req)
        End Function
        
        Public Function ObtenerVuelosElemenAsync(ByVal req As ServiceReference1.TempBitacoraCuartoRequest) As System.Threading.Tasks.Task(Of ServiceReference1.TempBitacoraCuartoResponse) Implements ServiceReference1.ControlTempSoap.ObtenerVuelosElemenAsync
            Return MyBase.Channel.ObtenerVuelosElemenAsync(req)
        End Function
        
        Public Function ObtenerParametrosNoti(ByVal req As ServiceReference1.NotificacionTempRequest) As ServiceReference1.NotificacionTempResponse Implements ServiceReference1.ControlTempSoap.ObtenerParametrosNoti
            Return MyBase.Channel.ObtenerParametrosNoti(req)
        End Function
        
        Public Function ObtenerParametrosNotiAsync(ByVal req As ServiceReference1.NotificacionTempRequest) As System.Threading.Tasks.Task(Of ServiceReference1.NotificacionTempResponse) Implements ServiceReference1.ControlTempSoap.ObtenerParametrosNotiAsync
            Return MyBase.Channel.ObtenerParametrosNotiAsync(req)
        End Function
        
        Public Function MantNotificacionTemp(ByVal req As ServiceReference1.NotificacionTempRequest) As ServiceReference1.NotificacionTempResponse Implements ServiceReference1.ControlTempSoap.MantNotificacionTemp
            Return MyBase.Channel.MantNotificacionTemp(req)
        End Function
        
        Public Function MantNotificacionTempAsync(ByVal req As ServiceReference1.NotificacionTempRequest) As System.Threading.Tasks.Task(Of ServiceReference1.NotificacionTempResponse) Implements ServiceReference1.ControlTempSoap.MantNotificacionTempAsync
            Return MyBase.Channel.MantNotificacionTempAsync(req)
        End Function
        
        Public Function ObtenerRegCuartProduc() As ServiceReference1.NotificacionTempResponse Implements ServiceReference1.ControlTempSoap.ObtenerRegCuartProduc
            Return MyBase.Channel.ObtenerRegCuartProduc
        End Function
        
        Public Function ObtenerRegCuartProducAsync() As System.Threading.Tasks.Task(Of ServiceReference1.NotificacionTempResponse) Implements ServiceReference1.ControlTempSoap.ObtenerRegCuartProducAsync
            Return MyBase.Channel.ObtenerRegCuartProducAsync
        End Function
    End Class
End Namespace
